// apps/web/src/features/agents/AgentDetailPage.tsx
import { useEffect, useState, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeftIcon, ArrowPathIcon, CheckIcon } from '@heroicons/react/24/outline';
import { PageHeader } from '../../components/PageHeader';
import { Tabs } from '../../components/Tabs';
import { Select } from '../../components/Select';
import { Textarea } from '../../components/Textarea';
import { Switch } from '../../components/Switch';
import { Button } from '../../components/Button';
import { Badge } from '../../components/Badge';
import { Spinner } from '../../components/Spinner';
import { ModelCombobox } from '../../components/ModelCombobox';
import { useToast } from '../../components/Toast';
import { api } from '../../lib/api';
import { formatDateTime, formatMoney, formatNumber } from '../../lib/format';
import { cn } from '../../lib/cn';
import { AgentTestPanel } from './AgentTestPanel';
import type { LLMEndpoint } from '../endpoints/EndpointsPage';

interface AgentConfig {
  id: string;
  name: string;
  role?: string;
  description?: string;
  endpointId: string | null;
  endpoint?: { id: string; name: string };
  fallbackEndpointId: string | null;
  model: string;
  systemPrompt: string;
  userPromptTemplate: string;
  params: Record<string, unknown>;
  enabled: boolean;
  variables?: string[];
  version: number;
  updatedAt: string;
}

interface AgentRunHistory {
  id: string;
  agentName: string;
  status: 'ok' | 'fallback' | 'failed';
  tokensIn: number;
  tokensOut: number;
  costUsd: number;
  latencyMs: number;
  createdAt: string;
  endpointId?: string;
  model?: string;
  error?: string | null;
}

export function AgentDetailPage() {
  const { id = '' } = useParams<{ id: string }>();
  const qc = useQueryClient();
  const toast = useToast();
  const [tab, setTab] = useState<'config' | 'test' | 'history'>('config');

  const { data: agent, isLoading } = useQuery({
    queryKey: ['agent', id],
    queryFn: () => api.get<AgentConfig>(`/agents/${id}`),
    enabled: !!id,
  });

  const { data: endpoints = [] } = useQuery({
    queryKey: ['endpoints'],
    queryFn: () => api.get<LLMEndpoint[]>('/endpoints'),
  });

  return (
    <div>
      <PageHeader
        title={agent?.name ?? 'Agent'}
        description={agent?.description ?? agent?.role ?? 'Карточка агента'}
        breadcrumbs={
          <Link to="/agents" className="inline-flex items-center gap-1 text-slate-500 hover:text-slate-700">
            <ArrowLeftIcon className="h-3.5 w-3.5" />
            Все агенты
          </Link>
        }
        actions={agent && <Badge tone="indigo">v{agent.version}</Badge>}
      />
      {isLoading || !agent ? (
        <div className="flex h-48 items-center justify-center">
          <Spinner className="text-brand-500" />
        </div>
      ) : (
        <div>
          <Tabs
            tabs={[
              { key: 'config', label: 'Config' },
              { key: 'test', label: 'Test' },
              { key: 'history', label: 'История' },
            ]}
            current={tab}
            onChange={(k) => setTab(k as typeof tab)}
          />
          <div className="mt-6">
            {tab === 'config' && (
              <ConfigForm
                agent={agent}
                endpoints={endpoints}
                onSaved={() => {
                  qc.invalidateQueries({ queryKey: ['agent', id] });
                  qc.invalidateQueries({ queryKey: ['agents'] });
                  toast.success('Конфиг сохранён', `Версия v${(agent.version ?? 0) + 1}`);
                }}
              />
            )}
            {tab === 'test' && <AgentTestPanel agent={agent} />}
            {tab === 'history' && <HistoryPanel agentId={agent.id} agentName={agent.name} />}
          </div>
        </div>
      )}
    </div>
  );
}

function ConfigForm({
  agent,
  endpoints,
  onSaved,
}: {
  agent: AgentConfig;
  endpoints: LLMEndpoint[];
  onSaved: () => void;
}) {
  const toast = useToast();
  const [endpointId, setEndpointId] = useState(agent.endpointId ?? '');
  const [fallbackId, setFallbackId] = useState(agent.fallbackEndpointId ?? '');
  const [model, setModel] = useState(agent.model);
  const [systemPrompt, setSystemPrompt] = useState(agent.systemPrompt);
  const [userTemplate, setUserTemplate] = useState(agent.userPromptTemplate);
  const [enabled, setEnabled] = useState(agent.enabled);
  const [paramsJson, setParamsJson] = useState(JSON.stringify(agent.params ?? {}, null, 2));
  const [paramsError, setParamsError] = useState<string | null>(null);

  useEffect(() => {
    setEndpointId(agent.endpointId ?? '');
    setFallbackId(agent.fallbackEndpointId ?? '');
    setModel(agent.model);
    setSystemPrompt(agent.systemPrompt);
    setUserTemplate(agent.userPromptTemplate);
    setEnabled(agent.enabled);
    setParamsJson(JSON.stringify(agent.params ?? {}, null, 2));
  }, [agent]);

  const usedVars = useMemo(() => extractVars(`${systemPrompt}\n${userTemplate}`), [systemPrompt, userTemplate]);
  const missing = (agent.variables ?? []).filter((v) => !usedVars.has(v));

  const mut = useMutation({
    mutationFn: () => {
      let params: unknown = {};
      try {
        params = JSON.parse(paramsJson || '{}');
        setParamsError(null);
      } catch (e) {
        setParamsError((e as Error).message);
        throw e;
      }
      return api.patch<AgentConfig>(`/agents/${agent.id}`, {
        endpointId: endpointId || null,
        fallbackEndpointId: fallbackId || null,
        model,
        systemPrompt,
        userPromptTemplate: userTemplate,
        enabled,
        params,
      });
    },
    onSuccess: () => onSaved(),
    onError: (e: Error) => toast.error('Не удалось сохранить', e.message),
  });

  const epOptions = endpoints.map((e) => ({ value: e.id, label: `${e.name} (${e.provider})` }));

  return (
    <div className="space-y-6">
      <div className="card-padded">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <Select
            label="Endpoint"
            value={endpointId}
            onChange={(e) => setEndpointId(e.target.value)}
            options={[{ value: '', label: '— не задан —' }, ...epOptions]}
          />
          <Select
            label="Fallback endpoint"
            value={fallbackId}
            onChange={(e) => setFallbackId(e.target.value)}
            options={[{ value: '', label: '— нет —' }, ...epOptions]}
          />
          <ModelCombobox
            label="Модель"
            endpointId={endpointId || null}
            value={model}
            onChange={setModel}
            helpText="Список моделей подгружается из выбранного endpoint. Можно ввести свой id."
          />
          <div className="flex items-end">
            <Switch
              checked={enabled}
              onChange={setEnabled}
              label="Включён"
              description="Если выключен — агент возвращает fallback или роняет пайплайн."
            />
          </div>
        </div>
      </div>

      <div className="card-padded">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-semibold text-slate-900">System prompt</h3>
          <VarsHelp declared={agent.variables} used={usedVars} missing={missing} />
        </div>
        <Textarea
          rows={10}
          fontMono
          className="mt-3"
          value={systemPrompt}
          onChange={(e) => setSystemPrompt(e.target.value)}
        />
        <div className="mt-2 text-xs text-slate-500">
          <PromptPreview text={systemPrompt} />
        </div>
      </div>

      <div className="card-padded">
        <h3 className="text-sm font-semibold text-slate-900">User prompt template</h3>
        <Textarea
          rows={8}
          fontMono
          className="mt-3"
          value={userTemplate}
          onChange={(e) => setUserTemplate(e.target.value)}
        />
        <div className="mt-2 text-xs text-slate-500">
          <PromptPreview text={userTemplate} />
        </div>
      </div>

      <div className="card-padded">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-semibold text-slate-900">Params (JSON)</h3>
          <span className="text-xs text-slate-500">temperature, max_tokens, top_p, json_schema, специфичные…</span>
        </div>
        <Textarea
          rows={10}
          fontMono
          className="mt-3"
          value={paramsJson}
          onChange={(e) => setParamsJson(e.target.value)}
          error={paramsError ?? undefined}
        />
      </div>

      <div className="flex items-center justify-between gap-3">
        <div className="text-xs text-slate-500">Обновлён: {formatDateTime(agent.updatedAt)}</div>
        <div className="flex items-center gap-2">
          <Button variant="secondary" onClick={() => window.location.reload()} leftIcon={<ArrowPathIcon className="h-4 w-4" />}>
            Сбросить
          </Button>
          <Button onClick={() => mut.mutate()} loading={mut.isPending} leftIcon={<CheckIcon className="h-4 w-4" />}>
            Сохранить новую версию
          </Button>
        </div>
      </div>
    </div>
  );
}

function VarsHelp({
  declared,
  used,
  missing,
}: {
  declared?: string[];
  used: Set<string>;
  missing: string[];
}) {
  if (!declared || declared.length === 0) return null;
  return (
    <div className="flex flex-wrap items-center gap-1.5 text-xs">
      <span className="text-slate-500">Vars:</span>
      {declared.map((v) => {
        const isUsed = used.has(v);
        return (
          <code
            key={v}
            className={cn(
              'rounded-md px-1.5 py-0.5 font-mono ring-1',
              isUsed
                ? 'bg-emerald-50 text-emerald-700 ring-emerald-200'
                : 'bg-rose-50 text-rose-700 ring-rose-200',
            )}
          >
            {`{{${v}}}`}
          </code>
        );
      })}
      {missing.length > 0 && (
        <span className="text-rose-600">не использованы: {missing.length}</span>
      )}
    </div>
  );
}

function PromptPreview({ text }: { text: string }) {
  const parts = text.split(/(\{\{[a-zA-Z_][\w]*\}\})/g);
  if (parts.length <= 1) return null;
  return (
    <span>
      Подсветка переменных:{' '}
      {parts
        .filter((p) => /^\{\{[a-zA-Z_][\w]*\}\}$/.test(p))
        .map((p, i) => (
          <code key={i} className="mr-1 rounded bg-brand-50 px-1.5 py-0.5 font-mono text-[11px] text-brand-700 ring-1 ring-brand-200">
            {p}
          </code>
        ))}
    </span>
  );
}

function extractVars(s: string): Set<string> {
  const set = new Set<string>();
  const re = /\{\{([a-zA-Z_][\w]*)\}\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(s)) !== null) {
    if (m[1]) set.add(m[1]);
  }
  return set;
}

function HistoryPanel({ agentId, agentName }: { agentId: string; agentName: string }) {
  const { data = [], isLoading } = useQuery({
    queryKey: ['agent-history', agentId],
    queryFn: () => api.get<AgentRunHistory[]>(`/agents/${agentId}/history?limit=50`),
  });
  if (isLoading) {
    return (
      <div className="flex h-32 items-center justify-center">
        <Spinner className="text-brand-500" />
      </div>
    );
  }
  if (data.length === 0) {
    return (
      <div className="card">
        <div className="px-6 py-12 text-center text-sm text-slate-500">
          Пока нет запусков агента <code className="font-mono">{agentName}</code>.
        </div>
      </div>
    );
  }
  return (
    <div className="card overflow-hidden">
      <table className="min-w-full divide-y divide-slate-200">
        <thead className="bg-slate-50">
          <tr>
            <th className="px-4 py-3 text-left text-xs font-semibold uppercase text-slate-500">Когда</th>
            <th className="px-4 py-3 text-left text-xs font-semibold uppercase text-slate-500">Статус</th>
            <th className="px-4 py-3 text-left text-xs font-semibold uppercase text-slate-500">Модель</th>
            <th className="px-4 py-3 text-right text-xs font-semibold uppercase text-slate-500">Tokens in/out</th>
            <th className="px-4 py-3 text-right text-xs font-semibold uppercase text-slate-500">Latency</th>
            <th className="px-4 py-3 text-right text-xs font-semibold uppercase text-slate-500">Cost</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100 bg-white">
          {data.map((h) => (
            <tr key={h.id}>
              <td className="px-4 py-3 text-sm text-slate-700">{formatDateTime(h.createdAt)}</td>
              <td className="px-4 py-3">
                <Badge tone={h.status === 'ok' ? 'emerald' : h.status === 'fallback' ? 'amber' : 'rose'}>
                  {h.status}
                </Badge>
              </td>
              <td className="px-4 py-3 font-mono text-xs text-slate-700">{h.model ?? '—'}</td>
              <td className="px-4 py-3 text-right text-sm text-slate-700">
                {formatNumber(h.tokensIn)} / {formatNumber(h.tokensOut)}
              </td>
              <td className="px-4 py-3 text-right text-sm text-slate-700">{h.latencyMs} мс</td>
              <td className="px-4 py-3 text-right text-sm text-slate-700">{formatMoney(h.costUsd)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// apps/web/src/features/agents/AgentDetailPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import PageHead from '../../components/PageHead.vue';
import Tabs from '../../components/Tabs.vue';
import Field from '../../components/Field.vue';
import SelectInput from '../../components/SelectInput.vue';
import TextareaInput from '../../components/TextareaInput.vue';
import Switch from '../../components/Switch.vue';
import ModelCombobox from '../../components/ModelCombobox.vue';
import Pill from '../../components/Pill.vue';
import Spinner from '../../components/Spinner.vue';
import Icon from '../../components/Icon.vue';
import AgentTestPanel from './AgentTestPanel.vue';
import { api } from '../../lib/api';
import { toast } from '../../lib/toast';
import { formatDateTime, formatMoney, formatNumber } from '../../lib/format';
import type { AgentConfig, AgentRunHistory } from './types';
import type { LLMEndpoint } from '../endpoints/types';

const route = useRoute();
const router = useRouter();
const qc = useQueryClient();

const id = computed(() => route.params.id as string);
const tab = ref<'config' | 'test' | 'history'>('config');

const { data: agent, isLoading } = useQuery({
  queryKey: ['agent', id],
  queryFn: () => api.get<AgentConfig>(`/agents/${id.value}`),
  enabled: computed(() => !!id.value),
});

const { data: endpoints } = useQuery({
  queryKey: ['endpoints'],
  queryFn: () => api.get<LLMEndpoint[]>('/endpoints'),
});

const endpointId = ref('');
const fallbackId = ref('');
const model = ref('');
const systemPrompt = ref('');
const userTemplate = ref('');
const enabled = ref(true);
const paramsJson = ref('{}');
const paramsError = ref<string | null>(null);

watch(
  () => agent.value,
  (a) => {
    if (!a) return;
    endpointId.value = a.endpointId ?? '';
    fallbackId.value = a.fallbackEndpointId ?? '';
    model.value = a.model;
    systemPrompt.value = a.systemPrompt;
    userTemplate.value = a.userPromptTemplate;
    enabled.value = a.enabled;
    paramsJson.value = JSON.stringify(a.params ?? {}, null, 2);
  },
  { immediate: true },
);

const epOptions = computed(() => [
  { value: '', label: '— не задан —' },
  ...((endpoints.value ?? []).map((e) => ({ value: e.id, label: `${e.name} (${e.provider})` }))),
]);

const fallbackOptions = computed(() => [
  { value: '', label: '— нет —' },
  ...((endpoints.value ?? []).map((e) => ({ value: e.id, label: `${e.name} (${e.provider})` }))),
]);

const tabsList = [
  { id: 'config', label: 'Config' },
  { id: 'test', label: 'Test' },
  { id: 'history', label: 'История' },
];

const usedVars = computed(() => extractVars(`${systemPrompt.value}\n${userTemplate.value}`));
const declared = computed(() => agent.value?.variables ?? []);
const missing = computed(() => declared.value.filter((v) => !usedVars.value.has(v)));

const saveMut = useMutation({
  mutationFn: () => {
    let params: unknown = {};
    try {
      params = JSON.parse(paramsJson.value || '{}');
      paramsError.value = null;
    } catch (e) {
      paramsError.value = (e as Error).message;
      throw e;
    }
    return api.patch<AgentConfig>(`/agents/${id.value}`, {
      endpointId: endpointId.value || null,
      fallbackEndpointId: fallbackId.value || null,
      model: model.value,
      systemPrompt: systemPrompt.value,
      userPromptTemplate: userTemplate.value,
      enabled: enabled.value,
      params,
    });
  },
  onSuccess: () => {
    qc.invalidateQueries({ queryKey: ['agent', id.value] });
    qc.invalidateQueries({ queryKey: ['agents'] });
    toast.success('Конфиг сохранён', `Версия v${(agent.value?.version ?? 0) + 1}`);
  },
  onError: (e: Error) => toast.error('Не удалось сохранить', e.message),
});

const { data: history, isLoading: historyLoading } = useQuery({
  queryKey: ['agent-history', id],
  queryFn: () => api.get<AgentRunHistory[]>(`/agents/${id.value}/history?limit=50`),
  enabled: computed(() => tab.value === 'history' && !!id.value),
});

function extractVars(s: string): Set<string> {
  const set = new Set<string>();
  const re = /\{\{([a-zA-Z_][\w]*)\}\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(s)) !== null) if (m[1]) set.add(m[1]);
  return set;
}

function fmtVar(v: string): string {
  return `{{${v}}}`;
}

function reset(): void {
  if (!agent.value) return;
  endpointId.value = agent.value.endpointId ?? '';
  fallbackId.value = agent.value.fallbackEndpointId ?? '';
  model.value = agent.value.model;
  systemPrompt.value = agent.value.systemPrompt;
  userTemplate.value = agent.value.userPromptTemplate;
  enabled.value = agent.value.enabled;
  paramsJson.value = JSON.stringify(agent.value.params ?? {}, null, 2);
  paramsError.value = null;
}
</script>

<template>
  <PageHead :title="agent?.name ?? 'Agent'" :sub="agent?.description ?? agent?.role ?? 'Карточка агента'">
    <template #actions>
      <button class="btn" @click="router.push('/agents')"><Icon name="arrow_left" :size="12" /><span>Все агенты</span></button>
      <button class="btn"><Icon name="copy" :size="12" /><span>Дублировать</span></button>
      <Pill v-if="agent" cls="accent" :label="`v${agent.version}`" :dot="false" />
    </template>
  </PageHead>

  <div v-if="isLoading || !agent" class="center"><Spinner /></div>
  <template v-else>
    <Tabs :tabs="tabsList" :active="tab" @change="(id) => (tab = id as any)" />

    <div v-if="tab === 'config'" class="cards" style="grid-template-columns: 1fr;">
      <div class="card">
        <div class="card-head"><Icon name="sliders" :size="12" /><span>Endpoint и модель</span></div>
        <div class="card-body">
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
            <Field label="Endpoint">
              <SelectInput v-model="endpointId" :options="epOptions" />
            </Field>
            <Field label="Fallback endpoint">
              <SelectInput v-model="fallbackId" :options="fallbackOptions" />
            </Field>
            <ModelCombobox
              :endpoint-id="endpointId || null"
              v-model="model"
              label="Модель"
              help="Список моделей подгружается из выбранного endpoint. Можно ввести свой id."
            />
            <Field label="Включён">
              <div style="display: flex; align-items: center; gap: 10px; padding: 4px 0;">
                <Switch v-model="enabled" />
                <span class="muted" style="font-size: 11.5px;">Если выключен — агент возвращает fallback или роняет пайплайн.</span>
              </div>
            </Field>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-head">
          <Icon name="edit" :size="12" /><span>System prompt</span>
          <div class="actions" v-if="declared.length">
            <span class="muted-2" style="font-size: 10.5px;">Vars:</span>
            <code
              v-for="v in declared"
              :key="v"
              class="mono"
              :style="{
                padding: '1px 5px',
                fontSize: '10.5px',
                borderRadius: '3px',
                background: usedVars.has(v) ? 'var(--ok-bg)' : 'var(--bad-bg)',
                color: usedVars.has(v) ? 'var(--ok)' : 'var(--bad)',
                border: '1px solid',
                borderColor: usedVars.has(v) ? 'var(--ok-line)' : 'var(--bad-line)',
              }"
            >{{ fmtVar(v) }}</code>
            <span v-if="missing.length" class="field-error" style="font-size: 10.5px;">не использованы: {{ missing.length }}</span>
          </div>
        </div>
        <div class="card-body">
          <TextareaInput v-model="systemPrompt" :rows="10" mono />
        </div>
      </div>

      <div class="card">
        <div class="card-head"><Icon name="edit" :size="12" /><span>User prompt template</span></div>
        <div class="card-body">
          <TextareaInput v-model="userTemplate" :rows="8" mono />
        </div>
      </div>

      <div class="card">
        <div class="card-head">
          <Icon name="sliders" :size="12" /><span>Params (JSON)</span>
          <div class="actions"><span class="muted-2" style="font-size: 10.5px;">temperature, max_tokens, top_p, json_schema…</span></div>
        </div>
        <div class="card-body">
          <Field :error="paramsError">
            <TextareaInput v-model="paramsJson" :rows="10" mono :error="!!paramsError" />
          </Field>
        </div>
      </div>

      <div style="display: flex; align-items: center; justify-content: space-between; padding: 0 22px 22px;">
        <div class="muted-2" style="font-size: 11px;">Обновлён: {{ formatDateTime(agent.updatedAt) }}</div>
        <div style="display: flex; gap: 6px;">
          <button class="btn" @click="reset"><Icon name="refresh" :size="12" /><span>Сбросить</span></button>
          <button class="btn primary" :disabled="saveMut.isPending.value" @click="saveMut.mutate()">
            <span v-if="saveMut.isPending.value" class="spinner" />
            <Icon v-else name="check" :size="12" /><span>Сохранить новую версию</span>
          </button>
        </div>
      </div>
    </div>

    <div v-else-if="tab === 'test'" style="padding: 14px 22px 22px;">
      <AgentTestPanel :agent-id="agent.id" :agent-name="agent.name" />
    </div>

    <div v-else-if="tab === 'history'" style="padding: 14px 22px 22px;">
      <div v-if="historyLoading" class="center"><Spinner /></div>
      <div v-else-if="!history || history.length === 0" class="placeholder" style="min-height: 120px;">
        Пока нет запусков агента {{ agent.name }}.
      </div>
      <div v-else class="card" style="border-radius: var(--r-md);">
        <div class="table-wrap">
          <table class="tbl">
            <thead>
              <tr>
                <th>Когда</th>
                <th>Статус</th>
                <th>Модель</th>
                <th style="text-align: right;">Tokens in/out</th>
                <th style="text-align: right;">Latency</th>
                <th style="text-align: right;">Cost</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="h in history" :key="h.id">
                <td>{{ formatDateTime(h.createdAt) }}</td>
                <td><Pill :state="h.status === 'ok' ? 'ok' : h.status === 'fallback' ? 'paused' : 'failed'" :label="h.status" /></td>
                <td class="mono muted-2" style="font-size: 11px;">{{ h.model ?? '—' }}</td>
                <td class="mono" style="text-align: right;">{{ formatNumber(h.tokensIn) }} / {{ formatNumber(h.tokensOut) }}</td>
                <td class="mono" style="text-align: right;">{{ h.latencyMs }} мс</td>
                <td class="mono" style="text-align: right;">{{ formatMoney(h.costUsd) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </template>
</template>
