// apps/web/src/features/users/UsersPage.tsx
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PlusIcon, TrashIcon, PencilSquareIcon } from '@heroicons/react/24/outline';
import { PageHeader } from '../../components/PageHeader';
import { Button } from '../../components/Button';
import { Badge } from '../../components/Badge';
import { DataTable, type Column } from '../../components/DataTable';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { UserForm } from './UserForm';
import { useToast } from '../../components/Toast';
import { api } from '../../lib/api';
import { formatDateTime } from '../../lib/format';

export interface UserRow {
  id: string;
  email: string;
  role: 'admin' | 'operator' | 'viewer';
  createdAt: string;
  updatedAt: string;
}

export function UsersPage() {
  const qc = useQueryClient();
  const toast = useToast();
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<UserRow | null>(null);
  const [deleteFor, setDeleteFor] = useState<UserRow | null>(null);

  const { data = [], isLoading } = useQuery({
    queryKey: ['users'],
    queryFn: () => api.get<UserRow[]>('/users'),
  });

  const delMut = useMutation({
    mutationFn: (id: string) => api.del<void>(`/users/${id}`),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['users'] });
      toast.success('Пользователь удалён');
      setDeleteFor(null);
    },
  });

  const columns: Column<UserRow>[] = [
    {
      key: 'user',
      header: 'Пользователь',
      cell: (u) => (
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-900 text-xs font-semibold text-white">
            {u.email.slice(0, 2).toUpperCase()}
          </div>
          <div className="min-w-0">
            <div className="truncate font-medium text-slate-900">{u.email}</div>
          </div>
        </div>
      ),
    },
    {
      key: 'role',
      header: 'Роль',
      cell: (u) => (
        <Badge tone={u.role === 'admin' ? 'indigo' : u.role === 'operator' ? 'sky' : 'slate'}>{u.role}</Badge>
      ),
    },
    {
      key: 'created',
      header: 'Создан',
      cell: (u) => <span className="text-xs text-slate-500">{formatDateTime(u.createdAt)}</span>,
    },
    {
      key: 'actions',
      header: '',
      align: 'right',
      cell: (u) => (
        <div className="flex items-center justify-end gap-1">
          <button
            className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100"
            onClick={() => {
              setEditing(u);
              setFormOpen(true);
            }}
          >
            <PencilSquareIcon className="h-4 w-4" />
          </button>
          <button
            className="rounded-lg p-1.5 text-rose-500 hover:bg-rose-50"
            onClick={() => setDeleteFor(u)}
          >
            <TrashIcon className="h-4 w-4" />
          </button>
        </div>
      ),
    },
  ];

  return (
    <div>
      <PageHeader
        title="Пользователи"
        description="Операторы и роли. Admin может всё, operator ведёт диалоги, viewer только смотрит."
        actions={
          <Button leftIcon={<PlusIcon className="h-4 w-4" />} onClick={() => { setEditing(null); setFormOpen(true); }}>
            Добавить пользователя
          </Button>
        }
      />
      <DataTable
        columns={columns}
        rows={data}
        loading={isLoading}
        rowKey={(r) => r.id}
        emptyTitle="Пользователей пока нет"
        emptyDescription="Создайте операторов, чтобы передавать им подсказки и эскалации."
      />
      <UserForm
        open={formOpen}
        onClose={() => setFormOpen(false)}
        user={editing}
        onSaved={() => {
          qc.invalidateQueries({ queryKey: ['users'] });
          setFormOpen(false);
        }}
      />
      <ConfirmDialog
        open={!!deleteFor}
        onClose={() => setDeleteFor(null)}
        onConfirm={() => deleteFor && delMut.mutate(deleteFor.id)}
        title="Удалить пользователя?"
        description={`Учётка "${deleteFor?.email}" будет удалена. Связанные действия в audit_log сохраняются.`}
        confirmLabel="Удалить"
        destructive
        loading={delMut.isPending}
      />
    </div>
  );
}

// apps/web/src/features/users/UsersPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import PageHead from '../../components/PageHead.vue';
import Pill from '../../components/Pill.vue';
import Avatar from '../../components/Avatar.vue';
import Icon from '../../components/Icon.vue';
import Spinner from '../../components/Spinner.vue';
import EmptyState from '../../components/EmptyState.vue';
import ConfirmDialog from '../../components/ConfirmDialog.vue';
import UserForm from './UserForm.vue';
import { api } from '../../lib/api';
import { toast } from '../../lib/toast';
import { initials, formatDateTime } from '../../lib/format';
import { avatarColor } from '../../lib/state';
import type { UserRow } from './types';

const qc = useQueryClient();

const formOpen = ref(false);
const editing = ref<UserRow | null>(null);
const deleteFor = ref<UserRow | null>(null);

const { data, isLoading } = useQuery({
  queryKey: ['users'],
  queryFn: () => api.get<UserRow[]>('/users'),
});

const list = computed<UserRow[]>(() => data.value ?? []);

const delMut = useMutation({
  mutationFn: (id: string) => api.del<void>(`/users/${id}`),
  onSuccess: () => {
    qc.invalidateQueries({ queryKey: ['users'] });
    toast.success('Пользователь удалён');
    deleteFor.value = null;
  },
});

function openEdit(u: UserRow): void { editing.value = u; formOpen.value = true; }
function openNew(): void { editing.value = null; formOpen.value = true; }
</script>

<template>
  <PageHead title="Пользователи" sub="Операторы и роли. Admin может всё, operator ведёт диалоги, viewer только смотрит.">
    <template #actions>
      <button class="btn primary" @click="openNew"><Icon name="plus" :size="12" /><span>Добавить пользователя</span></button>
    </template>
  </PageHead>

  <div v-if="isLoading" class="center"><Spinner /></div>
  <EmptyState
    v-else-if="list.length === 0"
    title="Пользователей нет"
    description="Создайте операторов, чтобы передавать им подсказки и эскалации."
    icon="users"
  >
    <template #action>
      <button class="btn primary" @click="openNew"><Icon name="plus" :size="12" /><span>Добавить</span></button>
    </template>
  </EmptyState>
  <div v-else class="table-wrap">
    <table class="tbl">
      <thead>
        <tr>
          <th>Пользователь</th>
          <th>Роль</th>
          <th>Создан</th>
          <th style="width: 100px;"></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="u in list" :key="u.id">
          <td>
            <div style="display: flex; align-items: center; gap: 9px;">
              <Avatar :text="initials(u.email)" :color="avatarColor(u.id)" round />
              <div class="cell-strong ellipsis">{{ u.email }}</div>
            </div>
          </td>
          <td><Pill :state="u.role" /></td>
          <td class="muted-2 mono" style="font-size: 10.5px;">{{ formatDateTime(u.createdAt) }}</td>
          <td>
            <div style="display: flex; gap: 4px; justify-content: flex-end;">
              <button class="btn ghost icon-only sm" @click="openEdit(u)"><Icon name="edit" :size="12" /></button>
              <button class="btn ghost icon-only sm" @click="deleteFor = u" style="color: var(--bad);"><Icon name="trash" :size="12" /></button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <UserForm
    :open="formOpen"
    :user="editing"
    @close="formOpen = false"
    @saved="() => { formOpen = false; qc.invalidateQueries({ queryKey: ['users'] }); }"
  />
  <ConfirmDialog
    :open="!!deleteFor"
    title="Удалить пользователя?"
    :description="deleteFor ? `Учётка «${deleteFor.email}» будет удалена. Связанные действия в audit_log сохраняются.` : ''"
    confirm-label="Удалить"
    destructive
    :loading="delMut.isPending.value"
    @close="deleteFor = null"
    @confirm="deleteFor && delMut.mutate(deleteFor.id)"
  />
</template>
