// apps/web/src/components/ConfirmDialog.tsx
import { type ReactNode } from 'react';
import { Modal } from './Modal';
import { Button } from './Button';

interface Props {
  open: boolean;
  onClose: () => void;
  onConfirm: () => void;
  title: string;
  description?: ReactNode;
  confirmLabel?: string;
  cancelLabel?: string;
  destructive?: boolean;
  loading?: boolean;
}

export function ConfirmDialog({
  open,
  onClose,
  onConfirm,
  title,
  description,
  confirmLabel = 'Подтвердить',
  cancelLabel = 'Отмена',
  destructive,
  loading,
}: Props) {
  return (
    <Modal
      open={open}
      onClose={onClose}
      title={title}
      size="sm"
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={loading}>
            {cancelLabel}
          </Button>
          <Button
            variant={destructive ? 'danger' : 'primary'}
            onClick={onConfirm}
            loading={loading}
          >
            {confirmLabel}
          </Button>
        </>
      }
    >
      {description && <div className="text-sm text-slate-600">{description}</div>}
    </Modal>
  );
}

// apps/web/src/components/ConfirmDialog.vue
<script setup lang="ts">
import Modal from './Modal.vue';

withDefaults(
  defineProps<{
    open: boolean;
    title: string;
    description?: string;
    confirmLabel?: string;
    cancelLabel?: string;
    destructive?: boolean;
    loading?: boolean;
  }>(),
  {
    confirmLabel: 'Подтвердить',
    cancelLabel: 'Отмена',
  },
);

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'confirm'): void;
}>();
</script>

<template>
  <Modal :open="open" :title="title" size="sm" @close="emit('close')">
    <div v-if="description" style="font-size: 12.5px; color: var(--ink-2); line-height: 1.55;">{{ description }}</div>
    <template #footer>
      <button class="btn" :disabled="loading" @click="emit('close')">{{ cancelLabel }}</button>
      <button :class="['btn', destructive ? 'danger' : 'primary']" :disabled="loading" @click="emit('confirm')">
        <span v-if="loading" class="spinner" />
        <span>{{ confirmLabel }}</span>
      </button>
    </template>
  </Modal>
</template>
