// apps/web/src/components/DataTable.vue
<script setup lang="ts" generic="T">
import Spinner from './Spinner.vue';
import EmptyState from './EmptyState.vue';

defineProps<{
  rows: T[] | undefined;
  loading?: boolean;
  emptyTitle?: string;
  emptyDescription?: string;
  rowKey: (row: T) => string;
  selectedKey?: string | null;
  onRowClick?: ((row: T) => void) | null;
}>();
</script>

<template>
  <div v-if="loading" class="center">
    <Spinner /><span style="margin-left: 8px;">Загрузка…</span>
  </div>
  <EmptyState
    v-else-if="!rows || rows.length === 0"
    :title="emptyTitle ?? 'Пока пусто'"
    :description="emptyDescription"
    icon="inbox"
  >
    <template v-if="$slots['empty-action']" #action>
      <slot name="empty-action" />
    </template>
  </EmptyState>
  <div v-else class="table-wrap">
    <table class="tbl">
      <thead>
        <slot name="head" />
      </thead>
      <tbody>
        <tr
          v-for="row in rows"
          :key="rowKey(row)"
          :class="[
            onRowClick ? 'clickable' : '',
            selectedKey != null && rowKey(row) === selectedKey ? 'selected' : '',
          ]"
          @click="onRowClick && onRowClick(row)"
        >
          <slot name="row" :row="row" />
        </tr>
      </tbody>
    </table>
  </div>
</template>

// apps/web/src/components/DataTable.tsx
import { type ReactNode } from 'react';
import { cn } from '../lib/cn';
import { Spinner } from './Spinner';
import { EmptyState } from './EmptyState';

export interface Column<T> {
  key: string;
  header: ReactNode;
  cell: (row: T) => ReactNode;
  className?: string;
  width?: string;
  align?: 'left' | 'right' | 'center';
}

interface Props<T> {
  columns: Column<T>[];
  rows: T[] | undefined;
  loading?: boolean;
  emptyTitle?: string;
  emptyDescription?: string;
  emptyAction?: ReactNode;
  rowKey: (row: T) => string;
  onRowClick?: (row: T) => void;
}

export function DataTable<T>({
  columns,
  rows,
  loading,
  emptyTitle = 'Пока пусто',
  emptyDescription,
  emptyAction,
  rowKey,
  onRowClick,
}: Props<T>) {
  if (loading) {
    return (
      <div className="card flex h-48 items-center justify-center text-slate-500">
        <Spinner className="text-brand-500" />
        <span className="ml-2 text-sm">Загрузка…</span>
      </div>
    );
  }
  if (!rows || rows.length === 0) {
    return (
      <div className="card">
        <EmptyState title={emptyTitle} description={emptyDescription} action={emptyAction} />
      </div>
    );
  }
  return (
    <div className="card overflow-hidden">
      <div className="overflow-x-auto scrollbar-thin">
        <table className="min-w-full divide-y divide-slate-200">
          <thead className="bg-slate-50">
            <tr>
              {columns.map((c) => (
                <th
                  key={c.key}
                  scope="col"
                  className={cn(
                    'px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500',
                    c.align === 'right' ? 'text-right' : c.align === 'center' ? 'text-center' : 'text-left',
                    c.className,
                  )}
                  style={c.width ? { width: c.width } : undefined}
                >
                  {c.header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 bg-white">
            {rows.map((row) => (
              <tr
                key={rowKey(row)}
                onClick={onRowClick ? () => onRowClick(row) : undefined}
                className={cn('transition-colors', onRowClick && 'cursor-pointer hover:bg-slate-50')}
              >
                {columns.map((c) => (
                  <td
                    key={c.key}
                    className={cn(
                      'px-4 py-3 text-sm text-slate-700',
                      c.align === 'right' ? 'text-right' : c.align === 'center' ? 'text-center' : 'text-left',
                      c.className,
                    )}
                  >
                    {c.cell(row)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
