// apps/web/src/components/ModelCombobox.tsx
import { Fragment, useMemo, useState } from 'react';
import { Combobox, Transition } from '@headlessui/react';
import { useQuery } from '@tanstack/react-query';
import { CheckIcon, ChevronUpDownIcon, ExclamationTriangleIcon } from '@heroicons/react/20/solid';
import { api, ApiError } from '../lib/api';
import { cn } from '../lib/cn';

export interface ModelOption {
  id: string;
  name?: string;
  description?: string;
  contextLength?: number;
  pricing?: { promptPer1M?: number; completionPer1M?: number };
}

interface Props {
  /** Endpoint id whose `/models` we'll fetch. When falsy, the combobox is disabled. */
  endpointId: string | null | undefined;
  value: string;
  onChange: (next: string) => void;
  label?: string;
  helpText?: string;
  className?: string;
}

/**
 * Searchable combobox for picking an LLM model. Loads the catalogue from
 * `/endpoints/:id/models` (provider-aware: hits OpenRouter/openai-compat
 * `GET /models`, hardcoded list for Yandex). Always allows free-form input
 * so operators can type a model id the provider added recently.
 */
export function ModelCombobox({ endpointId, value, onChange, label, helpText, className }: Props) {
  const [query, setQuery] = useState('');

  const { data: models, isLoading, isError, error, refetch } = useQuery({
    queryKey: ['endpoint-models', endpointId],
    queryFn: () => api.get<ModelOption[]>(`/endpoints/${endpointId}/models`),
    enabled: !!endpointId,
    staleTime: 5 * 60_000,
    retry: false,
  });

  const filtered = useMemo<ModelOption[]>(() => {
    const list = models ?? [];
    const q = query.trim().toLowerCase();
    if (!q) return list.slice(0, 200);
    return list
      .filter((m) => {
        const haystack = `${m.id} ${m.name ?? ''} ${m.description ?? ''}`.toLowerCase();
        return haystack.includes(q);
      })
      .slice(0, 200);
  }, [models, query]);

  // Always allow the typed value as an option even if the catalogue doesn't
  // include it (operator might know about a freshly-added model).
  const allowFreeform =
    query.length > 0 && !filtered.some((m) => m.id === query);

  const errMsg = isError
    ? error instanceof ApiError
      ? `${error.code}: ${error.message}`
      : (error as Error)?.message
    : null;

  return (
    <div className={cn('w-full', className)}>
      {label && <label className="label-base">{label}</label>}
      <Combobox value={value} onChange={(v) => onChange(v ?? '')} disabled={!endpointId}>
        <div className={cn('relative', label && 'mt-1.5')}>
          <Combobox.Input
            className="input-base pr-9"
            displayValue={(v: string) => v}
            placeholder={endpointId ? 'Поиск модели…' : 'Сначала выберите endpoint'}
            onChange={(e) => setQuery(e.target.value)}
          />
          <Combobox.Button className="absolute inset-y-0 right-0 flex items-center pr-2">
            <ChevronUpDownIcon className="h-5 w-5 text-slate-400" aria-hidden />
          </Combobox.Button>
          <Transition
            as={Fragment}
            leave="transition ease-in duration-100"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
            afterLeave={() => setQuery('')}
          >
            <Combobox.Options className="absolute z-20 mt-1 max-h-72 w-full overflow-auto rounded-xl bg-white py-1 shadow-pop ring-1 ring-slate-200 focus:outline-none scrollbar-thin">
              {isLoading && (
                <div className="px-3 py-2 text-xs text-slate-500">Загрузка моделей…</div>
              )}
              {isError && (
                <div className="px-3 py-2 text-xs text-rose-600">
                  <div className="flex items-center gap-1.5">
                    <ExclamationTriangleIcon className="h-4 w-4" />
                    {errMsg ?? 'Не удалось получить список моделей'}
                  </div>
                  <button
                    type="button"
                    onClick={() => refetch()}
                    className="mt-1 text-brand-600 hover:underline"
                  >
                    Повторить
                  </button>
                </div>
              )}
              {!isLoading && !isError && filtered.length === 0 && !allowFreeform && (
                <div className="px-3 py-2 text-xs text-slate-500">Ничего не найдено</div>
              )}
              {allowFreeform && (
                <Combobox.Option
                  value={query}
                  className={({ active }) =>
                    cn(
                      'relative cursor-pointer select-none px-3 py-2 text-sm',
                      active ? 'bg-brand-50 text-brand-700' : 'text-slate-700',
                    )
                  }
                >
                  Использовать как есть: <code className="font-mono">{query}</code>
                </Combobox.Option>
              )}
              {filtered.map((m) => (
                <Combobox.Option
                  key={m.id}
                  value={m.id}
                  className={({ active }) =>
                    cn(
                      'relative cursor-pointer select-none px-3 py-2 text-sm',
                      active ? 'bg-brand-50 text-brand-900' : 'text-slate-800',
                    )
                  }
                >
                  {({ selected }) => (
                    <div className="flex items-start gap-2">
                      <CheckIcon
                        className={cn(
                          'mt-0.5 h-4 w-4 flex-shrink-0',
                          selected ? 'text-brand-600' : 'text-transparent',
                        )}
                        aria-hidden
                      />
                      <div className="min-w-0 flex-1">
                        <div className="truncate font-mono text-[12px]">{m.id}</div>
                        {m.name && m.name !== m.id && (
                          <div className="truncate text-[11px] text-slate-500">{m.name}</div>
                        )}
                        {(m.contextLength != null || m.pricing) && (
                          <div className="mt-0.5 flex flex-wrap gap-2 text-[10px] text-slate-500">
                            {m.contextLength != null && (
                              <span>ctx {formatCtx(m.contextLength)}</span>
                            )}
                            {m.pricing?.promptPer1M != null && (
                              <span>
                                ${m.pricing.promptPer1M.toFixed(2)}/1M in
                              </span>
                            )}
                            {m.pricing?.completionPer1M != null && (
                              <span>
                                ${m.pricing.completionPer1M.toFixed(2)}/1M out
                              </span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </Combobox.Option>
              ))}
            </Combobox.Options>
          </Transition>
        </div>
      </Combobox>
      {helpText && <p className="help-text">{helpText}</p>}
    </div>
  );
}

function formatCtx(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}k`;
  return String(n);
}

// apps/web/src/components/ModelCombobox.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useQuery } from '@tanstack/vue-query';
import Icon from './Icon.vue';
import { api, ApiError } from '../lib/api';

export interface ModelOption {
  id: string;
  name?: string;
  description?: string;
  contextLength?: number;
  pricing?: { promptPer1M?: number; completionPer1M?: number };
}

const props = defineProps<{
  endpointId: string | null | undefined;
  modelValue: string;
  label?: string;
  help?: string;
}>();

const emit = defineEmits<{ (e: 'update:modelValue', v: string): void }>();

const query = ref('');
const open = ref(false);
const root = ref<HTMLElement | null>(null);

const endpointEnabled = computed(() => !!props.endpointId);

const { data: models, isLoading, isError, error, refetch } = useQuery({
  queryKey: ['endpoint-models', () => props.endpointId],
  queryFn: () => api.get<ModelOption[]>(`/endpoints/${props.endpointId}/models`),
  enabled: endpointEnabled,
  staleTime: 5 * 60_000,
  retry: false,
});

const filtered = computed<ModelOption[]>(() => {
  const list = models.value ?? [];
  const q = query.value.trim().toLowerCase();
  if (!q) return list.slice(0, 200);
  return list
    .filter((m) => `${m.id} ${m.name ?? ''} ${m.description ?? ''}`.toLowerCase().includes(q))
    .slice(0, 200);
});

const allowFreeform = computed(() => query.value.length > 0 && !filtered.value.some((m) => m.id === query.value));

const errMsg = computed(() => {
  if (!isError.value) return null;
  const e = error.value;
  if (e instanceof ApiError) return `${e.code}: ${e.message}`;
  return (e as Error)?.message ?? null;
});

function pick(id: string): void {
  emit('update:modelValue', id);
  open.value = false;
  query.value = '';
}

watch(
  () => props.modelValue,
  (v) => {
    if (!open.value) query.value = v ?? '';
  },
  { immediate: true },
);

function onClickOutside(e: MouseEvent): void {
  if (!root.value) return;
  if (!root.value.contains(e.target as Node)) open.value = false;
}

onMounted(() => document.addEventListener('mousedown', onClickOutside));
onBeforeUnmount(() => document.removeEventListener('mousedown', onClickOutside));

function fmtCtx(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${Math.round(n / 1_000)}k`;
  return String(n);
}
</script>

<template>
  <div class="field-row" ref="root">
    <label v-if="label" class="field-label">{{ label }}</label>
    <div style="position: relative;">
      <input
        :class="['input', !endpointEnabled ? '' : '']"
        :value="open ? query : modelValue"
        :placeholder="endpointEnabled ? 'Поиск модели…' : 'Сначала выберите endpoint'"
        :disabled="!endpointEnabled"
        @input="(e) => { query = (e.target as HTMLInputElement).value; open = true; }"
        @focus="() => { open = true; query = modelValue; }"
        autocomplete="off"
      />
      <button
        type="button"
        class="btn ghost icon-only sm"
        style="position: absolute; right: 2px; top: 50%; transform: translateY(-50%);"
        @click="open = !open"
      >
        <Icon name="chev_up_down" :size="12" />
      </button>
      <div
        v-if="open"
        class="dropdown-menu"
        style="position: absolute; top: 100%; left: 0; right: 0; max-height: 320px; overflow: auto; padding: 4px;"
      >
        <div v-if="isLoading" style="padding: 8px 10px; font-size: 11px; color: var(--ink-3);">Загрузка моделей…</div>
        <div v-else-if="isError" style="padding: 8px 10px; font-size: 11px; color: var(--bad);">
          <div style="display: inline-flex; align-items: center; gap: 4px;">
            <Icon name="warn" :size="12" />
            <span>{{ errMsg ?? 'Не удалось получить список моделей' }}</span>
          </div>
          <button type="button" class="btn ghost sm" style="margin-top: 4px;" @click="refetch()">Повторить</button>
        </div>
        <button
          v-if="allowFreeform"
          type="button"
          class="dropdown-item"
          @click="pick(query)"
        >
          Использовать как есть: <code class="mono">{{ query }}</code>
        </button>
        <button
          v-for="m in filtered"
          :key="m.id"
          type="button"
          class="dropdown-item"
          @click="pick(m.id)"
        >
          <div style="display: flex; flex-direction: column; gap: 2px; min-width: 0; flex: 1;">
            <div class="mono ellipsis" style="font-size: 11.5px;">{{ m.id }}</div>
            <div v-if="m.name && m.name !== m.id" class="muted-2 ellipsis" style="font-size: 10.5px;">{{ m.name }}</div>
            <div v-if="m.contextLength != null || m.pricing" class="muted-2" style="font-size: 10px; display: flex; gap: 8px; flex-wrap: wrap;">
              <span v-if="m.contextLength != null">ctx {{ fmtCtx(m.contextLength) }}</span>
              <span v-if="m.pricing?.promptPer1M != null">${{ m.pricing.promptPer1M.toFixed(2) }}/1M in</span>
              <span v-if="m.pricing?.completionPer1M != null">${{ m.pricing.completionPer1M.toFixed(2) }}/1M out</span>
            </div>
          </div>
        </button>
        <div v-if="!isLoading && !isError && filtered.length === 0 && !allowFreeform" style="padding: 8px 10px; font-size: 11px; color: var(--ink-3);">
          Ничего не найдено
        </div>
      </div>
    </div>
    <div v-if="help" class="field-help">{{ help }}</div>
  </div>
</template>
