// apps/web/src/features/campaigns/CampaignsPage.tsx
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { PlusIcon, PlayIcon, PauseIcon } from '@heroicons/react/24/outline';
import { PageHeader } from '../../components/PageHeader';
import { Button } from '../../components/Button';
import { Badge } from '../../components/Badge';
import { StatusDot } from '../../components/StatusDot';
import { EmptyState } from '../../components/EmptyState';
import { Spinner } from '../../components/Spinner';
import { CampaignForm } from './CampaignForm';
import { useToast } from '../../components/Toast';
import { api } from '../../lib/api';
import { formatNumber, formatRelative, formatPct, truncate } from '../../lib/format';

export interface CampaignSchedule {
  tz?: string;
  workHours?: { start: string; end: string };
  days?: number[];
  maxPerDayPerAccount?: number;
}

export interface Campaign {
  id: string;
  name: string;
  goalText: string;
  valueProp: string;
  status: 'draft' | 'running' | 'paused' | 'finished';
  defaultMode: 'auto' | 'assisted' | 'manual';
  targetFilter?: Record<string, unknown>;
  outreachAccountPool?: string[];
  schedule?: CampaignSchedule;
  agentOverrides?: Record<string, unknown>;
  metrics?: { sent: number; replies: number; replyRate: number; qualified: number };
  createdAt: string;
  updatedAt: string;
}

export function CampaignsPage() {
  const qc = useQueryClient();
  const toast = useToast();
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<Campaign | null>(null);

  const { data: campaigns = [], isLoading } = useQuery({
    queryKey: ['campaigns'],
    queryFn: () => api.get<Campaign[]>('/campaigns'),
  });

  const runMut = useMutation({
    mutationFn: (id: string) => api.post<void>(`/campaigns/${id}/run`, {}),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['campaigns'] });
      toast.success('Кампания запущена');
    },
  });
  const pauseMut = useMutation({
    mutationFn: (id: string) => api.post<void>(`/campaigns/${id}/pause`, {}),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['campaigns'] });
      toast.info('Кампания на паузе');
    },
  });

  return (
    <div>
      <PageHeader
        title="Кампании"
        description="CustDev-кампании: цель, value-prop, фильтр сегмента, расписание, агент-оверрайды."
        actions={
          <Button leftIcon={<PlusIcon className="h-4 w-4" />} onClick={() => { setEditing(null); setFormOpen(true); }}>
            Новая кампания
          </Button>
        }
      />
      {isLoading ? (
        <div className="flex h-48 items-center justify-center">
          <Spinner className="text-brand-500" />
        </div>
      ) : campaigns.length === 0 ? (
        <div className="card">
          <EmptyState
            title="Кампаний пока нет"
            description="Создайте первую: цель — CustDev по продукту, фильтр — каналы и роли."
            action={
              <Button leftIcon={<PlusIcon className="h-4 w-4" />} onClick={() => setFormOpen(true)}>
                Создать
              </Button>
            }
          />
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          {campaigns.map((c) => (
            <div key={c.id} className="card-padded">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <Link to={`/campaigns/${c.id}`} className="text-base font-semibold text-slate-900 hover:text-brand-700">
                    {c.name}
                  </Link>
                  <div className="mt-1 flex flex-wrap items-center gap-2">
                    <StatusDot status={c.status} />
                    <Badge tone={c.defaultMode === 'auto' ? 'indigo' : c.defaultMode === 'assisted' ? 'violet' : 'amber'}>
                      mode: {c.defaultMode}
                    </Badge>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {c.status === 'running' ? (
                    <Button
                      size="sm"
                      variant="secondary"
                      leftIcon={<PauseIcon className="h-4 w-4" />}
                      onClick={() => pauseMut.mutate(c.id)}
                    >
                      Пауза
                    </Button>
                  ) : (
                    <Button
                      size="sm"
                      leftIcon={<PlayIcon className="h-4 w-4" />}
                      onClick={() => runMut.mutate(c.id)}
                    >
                      Запустить
                    </Button>
                  )}
                </div>
              </div>
              <p className="mt-3 line-clamp-2 text-sm text-slate-600">{c.goalText}</p>
              <div className="mt-2 text-xs text-slate-500">
                value-prop: <span className="text-slate-700">{truncate(c.valueProp, 100)}</span>
              </div>
              <div className="mt-4 grid grid-cols-4 gap-3">
                <Stat label="Sent" value={formatNumber(c.metrics?.sent ?? 0)} />
                <Stat label="Replies" value={formatNumber(c.metrics?.replies ?? 0)} />
                <Stat label="Reply-rate" value={formatPct(c.metrics?.replyRate ?? 0)} />
                <Stat label="Qualified" value={formatNumber(c.metrics?.qualified ?? 0)} />
              </div>
              <div className="mt-4 flex items-center justify-between text-xs text-slate-500">
                <span>Обновлена {formatRelative(c.updatedAt)}</span>
                <Link to={`/campaigns/${c.id}`} className="font-medium text-brand-600 hover:text-brand-500">
                  Подробнее →
                </Link>
              </div>
            </div>
          ))}
        </div>
      )}
      <CampaignForm
        open={formOpen}
        onClose={() => setFormOpen(false)}
        campaign={editing}
        onSaved={() => {
          qc.invalidateQueries({ queryKey: ['campaigns'] });
          setFormOpen(false);
        }}
      />
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl bg-slate-50 px-3 py-2 ring-1 ring-slate-200">
      <div className="text-[10px] font-medium uppercase tracking-wide text-slate-500">{label}</div>
      <div className="text-sm font-semibold text-slate-900 tabular-nums">{value}</div>
    </div>
  );
}

// apps/web/src/features/campaigns/CampaignsPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import { useRouter } from 'vue-router';
import PageHead from '../../components/PageHead.vue';
import Pill from '../../components/Pill.vue';
import Icon from '../../components/Icon.vue';
import Spinner from '../../components/Spinner.vue';
import EmptyState from '../../components/EmptyState.vue';
import CampaignForm from './CampaignForm.vue';
import { api } from '../../lib/api';
import { toast } from '../../lib/toast';
import { formatNumber, formatPct, formatRelative, truncate } from '../../lib/format';
import type { Campaign } from './types';

const qc = useQueryClient();
const router = useRouter();

const formOpen = ref(false);
const editing = ref<Campaign | null>(null);

const { data: campaigns, isLoading } = useQuery({
  queryKey: ['campaigns'],
  queryFn: () => api.get<Campaign[]>('/campaigns'),
});

const list = computed<Campaign[]>(() => campaigns.value ?? []);

const runMut = useMutation({
  mutationFn: (id: string) => api.post<void>(`/campaigns/${id}/run`, {}),
  onSuccess: () => { qc.invalidateQueries({ queryKey: ['campaigns'] }); toast.success('Кампания запущена'); },
});
const pauseMut = useMutation({
  mutationFn: (id: string) => api.post<void>(`/campaigns/${id}/pause`, {}),
  onSuccess: () => { qc.invalidateQueries({ queryKey: ['campaigns'] }); toast.info('Кампания на паузе'); },
});

function openEdit(c: Campaign): void { editing.value = c; formOpen.value = true; }
function openNew(): void { editing.value = null; formOpen.value = true; }
</script>

<template>
  <PageHead title="Кампании" :sub="`${list.length} кампаний · ${list.filter((c) => c.status === 'running').length} активных`">
    <template #actions>
      <button class="btn"><Icon name="copy" :size="12" /><span>Дублировать</span></button>
      <button class="btn primary" @click="openNew">
        <Icon name="plus" :size="12" /><span>Новая кампания</span>
      </button>
    </template>
  </PageHead>

  <div v-if="isLoading" class="center"><Spinner /></div>
  <EmptyState
    v-else-if="list.length === 0"
    title="Кампаний нет"
    description="Создайте первую: цель — CustDev по продукту, фильтр — каналы и роли."
    icon="zap"
  >
    <template #action>
      <button class="btn primary" @click="openNew"><Icon name="plus" :size="12" /><span>Создать</span></button>
    </template>
  </EmptyState>

  <div v-else class="cards" style="grid-template-columns: 1fr 1fr;">
    <div v-for="c in list" :key="c.id" class="card">
      <div class="card-head" style="cursor: pointer;" @click="router.push(`/campaigns/${c.id}`)">
        <span style="font-weight: 500; flex: 1;">{{ c.name }}</span>
        <Pill :state="c.status" />
        <Pill :state="c.defaultMode" />
        <div class="actions">
          <button class="btn ghost icon-only sm" title="Редактировать" @click.stop="openEdit(c)">
            <Icon name="edit" :size="11" />
          </button>
          <button v-if="c.status === 'running'" class="btn sm" :disabled="pauseMut.isPending.value" @click.stop="pauseMut.mutate(c.id)">
            <Icon name="pause" :size="11" /><span>Пауза</span>
          </button>
          <button v-else class="btn primary sm" :disabled="runMut.isPending.value" @click.stop="runMut.mutate(c.id)">
            <Icon name="play" :size="11" /><span>Запустить</span>
          </button>
        </div>
      </div>
      <div class="card-body">
        <p class="muted" style="font-size: 12.5px; line-height: 1.5; margin: 0 0 10px;">{{ truncate(c.goalText, 200) }}</p>
        <div class="muted-2" style="font-size: 11.5px; margin-bottom: 12px;">value-prop: <span style="color: var(--ink-2);">{{ truncate(c.valueProp, 120) }}</span></div>
        <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; margin-bottom: 8px;">
          <div style="padding: 6px 10px; background: var(--paper-2); border: 1px solid var(--line); border-radius: var(--r-sm);">
            <div class="muted-2" style="font-size: 10px; text-transform: uppercase;">Sent</div>
            <div class="mono cell-strong" style="font-size: 14px;">{{ formatNumber(c.metrics?.sent ?? 0) }}</div>
          </div>
          <div style="padding: 6px 10px; background: var(--paper-2); border: 1px solid var(--line); border-radius: var(--r-sm);">
            <div class="muted-2" style="font-size: 10px; text-transform: uppercase;">Replies</div>
            <div class="mono cell-strong" style="font-size: 14px; color: var(--ok);">{{ formatNumber(c.metrics?.replies ?? 0) }}</div>
          </div>
          <div style="padding: 6px 10px; background: var(--paper-2); border: 1px solid var(--line); border-radius: var(--r-sm);">
            <div class="muted-2" style="font-size: 10px; text-transform: uppercase;">Reply-rate</div>
            <div class="mono cell-strong" style="font-size: 14px;">{{ formatPct(c.metrics?.replyRate ?? 0) }}</div>
          </div>
          <div style="padding: 6px 10px; background: var(--paper-2); border: 1px solid var(--line); border-radius: var(--r-sm);">
            <div class="muted-2" style="font-size: 10px; text-transform: uppercase;">Qualified</div>
            <div class="mono cell-strong" style="font-size: 14px; color: var(--violet);">{{ formatNumber(c.metrics?.qualified ?? 0) }}</div>
          </div>
        </div>
        <div style="display: flex; align-items: center; justify-content: space-between; font-size: 11px; color: var(--ink-3);">
          <span>Обновлена {{ formatRelative(c.updatedAt) }}</span>
          <a class="btn ghost sm" @click="router.push(`/campaigns/${c.id}`)">Подробнее →</a>
        </div>
      </div>
    </div>
  </div>

  <CampaignForm
    :open="formOpen"
    :campaign="editing"
    @close="formOpen = false"
    @saved="() => { formOpen = false; qc.invalidateQueries({ queryKey: ['campaigns'] }); }"
  />
</template>
