// apps/web/src/features/dashboard/DashboardPage.tsx
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import {
  ArrowTrendingUpIcon,
  HashtagIcon,
  IdentificationIcon,
  ChatBubbleLeftRightIcon,
  CurrencyDollarIcon,
  PaperAirplaneIcon,
  ExclamationTriangleIcon,
  CheckBadgeIcon,
} from '@heroicons/react/24/outline';
import { PageHeader } from '../../components/PageHeader';
import { api } from '../../lib/api';
import { formatNumber, formatMoney, formatPct, formatRelative } from '../../lib/format';
import { Spinner } from '../../components/Spinner';
import { StatusDot } from '../../components/StatusDot';
import { cn } from '../../lib/cn';

interface DashboardData {
  channels: { total: number; new: number; scraping: number; extracted: number; failed: number };
  contacts: { total: number; reachableTg: number; manual: number };
  conversations: { active: number; assisted: number; manual: number; auto: number };
  campaigns: { running: number; paused: number };
  cost: { tokensToday: number; costTodayUsd: number; cost7dUsd: number };
  replyRate7d: number;
  recentActivity: Array<{
    id: string;
    type: 'channel_extracted' | 'message_sent' | 'reply' | 'escalation' | 'failed';
    title: string;
    subtitle?: string;
    at: string;
  }>;
}

const fallback: DashboardData = {
  channels: { total: 0, new: 0, scraping: 0, extracted: 0, failed: 0 },
  contacts: { total: 0, reachableTg: 0, manual: 0 },
  conversations: { active: 0, assisted: 0, manual: 0, auto: 0 },
  campaigns: { running: 0, paused: 0 },
  cost: { tokensToday: 0, costTodayUsd: 0, cost7dUsd: 0 },
  replyRate7d: 0,
  recentActivity: [],
};

export function DashboardPage() {
  const { data, isLoading } = useQuery({
    queryKey: ['dashboard'],
    queryFn: () => api.get<DashboardData>('/metrics/dashboard'),
    refetchInterval: 30_000,
  });

  const d = data ?? fallback;

  return (
    <div>
      <PageHeader
        title="Дашборд"
        description="Сводка по каналам, контактам, диалогам и стоимости агентов."
      />
      {isLoading && !data ? (
        <div className="flex h-48 items-center justify-center text-slate-500">
          <Spinner className="text-brand-500" />
        </div>
      ) : (
        <div className="space-y-6">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <StatCard
              label="Каналы"
              value={formatNumber(d.channels.total)}
              icon={<HashtagIcon className="h-5 w-5" />}
              hint={`${formatNumber(d.channels.extracted)} с контактами`}
              tone="indigo"
              to="/channels"
            />
            <StatCard
              label="Контакты"
              value={formatNumber(d.contacts.total)}
              icon={<IdentificationIcon className="h-5 w-5" />}
              hint={`${formatNumber(d.contacts.reachableTg)} TG · ${formatNumber(d.contacts.manual)} manual`}
              tone="emerald"
              to="/contacts"
            />
            <StatCard
              label="Активные диалоги"
              value={formatNumber(d.conversations.active)}
              icon={<ChatBubbleLeftRightIcon className="h-5 w-5" />}
              hint={`Assisted ${d.conversations.assisted} · Manual ${d.conversations.manual}`}
              tone="violet"
              to="/inbox"
            />
            <StatCard
              label="Стоимость / 7 дн."
              value={formatMoney(d.cost.cost7dUsd)}
              icon={<CurrencyDollarIcon className="h-5 w-5" />}
              hint={`${formatMoney(d.cost.costTodayUsd)} сегодня`}
              tone="amber"
            />
          </div>

          <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <div className="card-padded lg:col-span-2">
              <div className="flex items-center justify-between">
                <h2 className="text-sm font-semibold text-slate-900">Воронка каналов</h2>
                <Link to="/channels" className="text-xs font-medium text-brand-600 hover:text-brand-500">
                  Открыть список →
                </Link>
              </div>
              <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">
                <FunnelStep status="new" count={d.channels.new} />
                <FunnelStep status="scraping" count={d.channels.scraping} />
                <FunnelStep status="extracted" count={d.channels.extracted} />
                <FunnelStep status="failed" count={d.channels.failed} />
                <FunnelStep status="ready" count={d.channels.total - d.channels.new - d.channels.scraping - d.channels.failed} />
              </div>
              <div className="mt-6 h-32 rounded-xl bg-gradient-to-br from-brand-50 to-slate-50 ring-1 ring-slate-200 flex items-center justify-center text-xs text-slate-400">
                Здесь будет график активности (placeholder)
              </div>
            </div>

            <div className="card-padded">
              <div className="flex items-center justify-between">
                <h2 className="text-sm font-semibold text-slate-900">KPI диалогов</h2>
                <ArrowTrendingUpIcon className="h-4 w-4 text-slate-400" />
              </div>
              <ul className="mt-4 space-y-3">
                <KpiRow label="Reply-rate (7д)" value={formatPct(d.replyRate7d)} tone="emerald" />
                <KpiRow label="Кампании running" value={formatNumber(d.campaigns.running)} tone="indigo" />
                <KpiRow label="Tokens сегодня" value={formatNumber(d.cost.tokensToday)} tone="slate" />
                <KpiRow label="Conv. на оператора" value={formatNumber(d.conversations.manual)} tone="violet" />
              </ul>
            </div>
          </div>

          <div className="card-padded">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold text-slate-900">Последняя активность</h2>
              <Link to="/audit" className="text-xs font-medium text-brand-600 hover:text-brand-500">
                Полный аудит →
              </Link>
            </div>
            <div className="mt-4 divide-y divide-slate-100">
              {d.recentActivity.length === 0 ? (
                <div className="py-10 text-center text-sm text-slate-500">Активности пока нет</div>
              ) : (
                d.recentActivity.map((ev) => <ActivityRow key={ev.id} ev={ev} />)
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StatCard({
  label,
  value,
  icon,
  hint,
  tone,
  to,
}: {
  label: string;
  value: string;
  icon: React.ReactNode;
  hint?: string;
  tone: 'indigo' | 'emerald' | 'amber' | 'violet';
  to?: string;
}) {
  const toneCls =
    tone === 'indigo'
      ? 'bg-brand-50 text-brand-700'
      : tone === 'emerald'
      ? 'bg-emerald-50 text-emerald-700'
      : tone === 'amber'
      ? 'bg-amber-50 text-amber-800'
      : 'bg-violet-50 text-violet-700';
  const inner = (
    <div className="card-padded h-full transition-shadow hover:shadow-pop">
      <div className="flex items-start justify-between">
        <div>
          <div className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</div>
          <div className="mt-2 text-2xl font-semibold text-slate-900">{value}</div>
        </div>
        <div className={cn('rounded-xl p-2', toneCls)}>{icon}</div>
      </div>
      {hint && <div className="mt-3 text-xs text-slate-500">{hint}</div>}
    </div>
  );
  return to ? <Link to={to}>{inner}</Link> : inner;
}

function FunnelStep({ status, count }: { status: string; count: number }) {
  return (
    <div className="rounded-xl bg-slate-50 p-3 ring-1 ring-slate-200">
      <StatusDot status={status} />
      <div className="mt-2 text-xl font-semibold text-slate-900">{formatNumber(count)}</div>
    </div>
  );
}

function KpiRow({ label, value, tone }: { label: string; value: string; tone: 'emerald' | 'indigo' | 'slate' | 'violet' }) {
  const toneCls =
    tone === 'emerald'
      ? 'text-emerald-600'
      : tone === 'indigo'
      ? 'text-brand-600'
      : tone === 'violet'
      ? 'text-violet-600'
      : 'text-slate-600';
  return (
    <li className="flex items-center justify-between">
      <span className="text-sm text-slate-600">{label}</span>
      <span className={cn('text-sm font-semibold', toneCls)}>{value}</span>
    </li>
  );
}

function ActivityRow({ ev }: { ev: DashboardData['recentActivity'][number] }) {
  const Icon =
    ev.type === 'message_sent'
      ? PaperAirplaneIcon
      : ev.type === 'reply'
      ? ChatBubbleLeftRightIcon
      : ev.type === 'failed'
      ? ExclamationTriangleIcon
      : ev.type === 'escalation'
      ? ExclamationTriangleIcon
      : CheckBadgeIcon;
  const tone =
    ev.type === 'failed'
      ? 'text-rose-600 bg-rose-50'
      : ev.type === 'escalation'
      ? 'text-amber-700 bg-amber-50'
      : ev.type === 'reply'
      ? 'text-emerald-600 bg-emerald-50'
      : 'text-brand-600 bg-brand-50';
  return (
    <div className="flex items-start gap-3 py-3">
      <div className={cn('mt-0.5 rounded-lg p-2', tone)}>
        <Icon className="h-4 w-4" />
      </div>
      <div className="min-w-0 flex-1">
        <div className="text-sm font-medium text-slate-900 truncate">{ev.title}</div>
        {ev.subtitle && <div className="text-xs text-slate-500">{ev.subtitle}</div>}
      </div>
      <div className="text-xs text-slate-400 whitespace-nowrap">{formatRelative(ev.at)}</div>
    </div>
  );
}

// apps/web/src/features/dashboard/DashboardPage.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useQuery } from '@tanstack/vue-query';
import { useRouter } from 'vue-router';
import PageHead from '../../components/PageHead.vue';
import Pill from '../../components/Pill.vue';
import Spinner from '../../components/Spinner.vue';
import Icon from '../../components/Icon.vue';
import { api } from '../../lib/api';
import { formatMoney, formatNumber, formatPct, formatRelative } from '../../lib/format';
import type { DashboardData } from './types';
import type { IconName } from '../../lib/icons';

const router = useRouter();

const fallback: DashboardData = {
  channels: { total: 0, new: 0, scraping: 0, extracted: 0, failed: 0 },
  contacts: { total: 0, reachableTg: 0, manual: 0 },
  conversations: { active: 0, assisted: 0, manual: 0, auto: 0 },
  campaigns: { running: 0, paused: 0 },
  cost: { tokensToday: 0, costTodayUsd: 0, cost7dUsd: 0 },
  replyRate7d: 0,
  recentActivity: [],
};

const { data, isLoading } = useQuery({
  queryKey: ['dashboard'],
  queryFn: () => api.get<DashboardData>('/metrics/dashboard'),
  refetchInterval: 30_000,
});

const d = computed<DashboardData>(() => data.value ?? fallback);

const stats = computed(() => [
  { label: 'Каналы', value: formatNumber(d.value.channels.total), hint: `${formatNumber(d.value.channels.extracted)} с контактами`, to: '/channels', icon: 'layers', color: 'var(--accent-2)' },
  { label: 'Контакты', value: formatNumber(d.value.contacts.total), hint: `${formatNumber(d.value.contacts.reachableTg)} TG · ${formatNumber(d.value.contacts.manual)} manual`, to: '/contacts', icon: 'users_round', color: 'var(--ok)' },
  { label: 'Активные диалоги', value: formatNumber(d.value.conversations.active), hint: `Assisted ${d.value.conversations.assisted} · Manual ${d.value.conversations.manual}`, to: '/inbox', icon: 'chat', color: 'var(--violet)' },
  { label: 'Стоимость / 7д', value: formatMoney(d.value.cost.cost7dUsd), hint: `${formatMoney(d.value.cost.costTodayUsd)} сегодня`, icon: 'database', color: 'var(--warn)' },
] as Array<{ label: string; value: string; hint?: string; to?: string; icon: IconName; color: string }>);

const funnelSteps = computed(() => [
  { state: 'new', count: d.value.channels.new },
  { state: 'scraping', count: d.value.channels.scraping },
  { state: 'extracted', count: d.value.channels.extracted },
  { state: 'failed', count: d.value.channels.failed },
  { state: 'ready', count: Math.max(0, d.value.channels.total - d.value.channels.new - d.value.channels.scraping - d.value.channels.failed) },
]);

const kpiRows = computed(() => [
  { label: 'Reply-rate (7д)', value: formatPct(d.value.replyRate7d), color: 'var(--ok)' },
  { label: 'Кампании running', value: formatNumber(d.value.campaigns.running), color: 'var(--accent-2)' },
  { label: 'Tokens сегодня', value: formatNumber(d.value.cost.tokensToday), color: 'var(--ink-2)' },
  { label: 'Conv. на оператора', value: formatNumber(d.value.conversations.manual), color: 'var(--violet)' },
]);

function activityIcon(type: string): IconName {
  switch (type) {
    case 'message_sent': return 'send';
    case 'reply': return 'chat';
    case 'failed':
    case 'escalation': return 'warn';
    default: return 'check_circle';
  }
}

function activityTone(type: string): string {
  switch (type) {
    case 'failed': return 'var(--bad)';
    case 'escalation': return 'var(--warn)';
    case 'reply': return 'var(--ok)';
    default: return 'var(--accent-2)';
  }
}
</script>

<template>
  <PageHead title="Дашборд" sub="Сводка по каналам, контактам, диалогам и стоимости агентов" />

  <div v-if="isLoading && !data" class="center"><Spinner /></div>
  <div v-else class="cards" style="grid-template-columns: 1fr;">
    <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px;">
      <div
        v-for="s in stats"
        :key="s.label"
        class="card"
        :style="{ cursor: s.to ? 'pointer' : 'default' }"
        @click="s.to && router.push(s.to)"
      >
        <div style="padding: 14px 16px;">
          <div style="display: flex; justify-content: space-between; align-items: flex-start;">
            <div>
              <div class="muted-2" style="font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 500;">{{ s.label }}</div>
              <div class="mono" style="font-size: 22px; font-weight: 600; letter-spacing: -0.02em; margin-top: 6px;">{{ s.value }}</div>
            </div>
            <span :style="{ width: '28px', height: '28px', borderRadius: '6px', background: 'var(--paper-3)', color: s.color, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }">
              <Icon :name="s.icon" :size="14" />
            </span>
          </div>
          <div v-if="s.hint" class="muted-2" style="margin-top: 8px; font-size: 11px;">{{ s.hint }}</div>
        </div>
      </div>
    </div>

    <div style="display: grid; grid-template-columns: 2fr 1fr; gap: 12px;">
      <div class="card">
        <div class="card-head">
          <Icon name="layers" :size="12" /><span>Воронка каналов</span>
          <div class="actions"><a class="btn ghost sm" @click="router.push('/channels')">Открыть список →</a></div>
        </div>
        <div class="card-body">
          <div style="display: grid; grid-template-columns: repeat(5, 1fr); gap: 8px;">
            <div v-for="f in funnelSteps" :key="f.state" style="background: var(--paper-2); border: 1px solid var(--line); padding: 10px 12px; border-radius: var(--r-sm);">
              <Pill :state="f.state" />
              <div class="mono cell-strong" style="font-size: 18px; margin-top: 6px;">{{ formatNumber(f.count) }}</div>
            </div>
          </div>
          <div class="placeholder" style="margin-top: 14px; min-height: 80px;">График активности (placeholder)</div>
        </div>
      </div>
      <div class="card">
        <div class="card-head"><Icon name="trend" :size="12" /><span>KPI диалогов</span></div>
        <div class="card-body">
          <ul style="margin: 0; padding: 0; list-style: none; display: flex; flex-direction: column; gap: 8px;">
            <li v-for="r in kpiRows" :key="r.label" style="display: flex; align-items: center; justify-content: space-between; font-size: 12.5px;">
              <span class="muted">{{ r.label }}</span>
              <span class="mono" :style="{ color: r.color, fontWeight: 600 }">{{ r.value }}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-head">
        <Icon name="clock" :size="12" /><span>Последняя активность</span>
        <div class="actions"><a class="btn ghost sm" @click="router.push('/audit')">Полный аудит →</a></div>
      </div>
      <div class="card-body">
        <div v-if="d.recentActivity.length === 0" class="muted" style="text-align: center; padding: 18px; font-size: 12.5px;">Активности пока нет</div>
        <div v-else style="display: flex; flex-direction: column;">
          <div
            v-for="ev in d.recentActivity"
            :key="ev.id"
            style="display: flex; align-items: flex-start; gap: 10px; padding: 9px 0; border-bottom: 1px solid var(--line);"
          >
            <span :style="{ width: '24px', height: '24px', borderRadius: '6px', background: 'var(--paper-2)', color: activityTone(ev.type), display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }">
              <Icon :name="activityIcon(ev.type)" :size="12" />
            </span>
            <div style="flex: 1; min-width: 0;">
              <div class="cell-strong ellipsis" style="font-size: 12.5px;">{{ ev.title }}</div>
              <div v-if="ev.subtitle" class="muted-2" style="font-size: 11px;">{{ ev.subtitle }}</div>
            </div>
            <span class="mono muted-2" style="font-size: 10.5px; white-space: nowrap;">{{ formatRelative(ev.at) }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
