// apps/web/src/features/inbox/ConversationView.tsx
import { useEffect, useMemo, useRef } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import {
  ChatBubbleLeftRightIcon,
  HashtagIcon,
  IdentificationIcon,
  EllipsisHorizontalIcon,
} from '@heroicons/react/24/outline';
import { Spinner } from '../../components/Spinner';
import { Badge } from '../../components/Badge';
import { StatusDot } from '../../components/StatusDot';
import { Dropdown } from '../../components/Dropdown';
import { ModeBadge } from './ModeBadge';
import { MessageBubble, type ChatMessage } from './MessageBubble';
import { SuggestionTray, type Suggestion } from './SuggestionTray';
import { useToast } from '../../components/Toast';
import { useRoom } from '../../lib/socket';
import { api } from '../../lib/api';
import { formatRelative } from '../../lib/format';
import type { ConversationListItem } from './ConversationList';

interface Props {
  conversation: ConversationListItem;
}

interface ConversationDetail extends ConversationListItem {
  summary?: string | null;
  meta?: Record<string, unknown>;
  tgAccount?: { label: string; phone: string };
  contact?: ConversationListItem['contact'];
}

export function ConversationView({ conversation }: Props) {
  const qc = useQueryClient();
  const toast = useToast();
  const cId = conversation.id;
  const room = `conversation:${cId}`;

  const { data: details } = useQuery({
    queryKey: ['conversation', cId],
    queryFn: () => api.get<ConversationDetail>(`/conversations/${cId}`),
  });
  const { data: messages = [], isLoading: msgsLoading } = useQuery({
    queryKey: ['conversation-messages', cId],
    queryFn: () => api.get<ChatMessage[]>(`/conversations/${cId}/messages`),
  });
  const { data: suggestions = [] } = useQuery({
    queryKey: ['conversation-suggestions', cId],
    queryFn: () => api.get<Suggestion[]>(`/conversations/${cId}/suggestions`),
  });

  const scrollRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages.length, cId]);

  useRoom(room, 'message.new', () => {
    qc.invalidateQueries({ queryKey: ['conversation-messages', cId] });
    qc.invalidateQueries({ queryKey: ['conversations'] });
  });
  useRoom(room, 'suggestion.new', () => {
    qc.invalidateQueries({ queryKey: ['conversation-suggestions', cId] });
  });
  useRoom(room, 'mode.changed', () => {
    qc.invalidateQueries({ queryKey: ['conversation', cId] });
  });

  const modeMut = useMutation({
    mutationFn: (mode: 'auto' | 'assisted' | 'manual') =>
      api.patch<void>(`/conversations/${cId}`, { mode }),
    onSuccess: (_v, mode) => {
      qc.invalidateQueries({ queryKey: ['conversation', cId] });
      qc.invalidateQueries({ queryKey: ['conversations'] });
      toast.success(`Режим: ${mode}`);
    },
  });
  const statusMut = useMutation({
    mutationFn: (status: 'active' | 'paused' | 'done' | 'failed') =>
      api.patch<void>(`/conversations/${cId}`, { status }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['conversation', cId] });
      qc.invalidateQueries({ queryKey: ['conversations'] });
    },
  });

  const c: ConversationDetail = details ?? conversation;
  const handle = c.contact?.channel?.handle ?? c.contact?.value ?? '—';
  const title = c.contact?.channel?.title ?? c.contact?.value ?? 'Без названия';
  const initials = title.slice(0, 2).toUpperCase();

  const dayGroups = useMemo(() => groupByDay(messages), [messages]);

  return (
    <div className="flex h-full flex-col">
      <header className="flex items-center justify-between gap-3 border-b border-slate-200 bg-white px-4 py-3">
        <div className="flex min-w-0 items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 text-sm font-semibold text-slate-700">
            {initials}
          </div>
          <div className="min-w-0">
            <div className="truncate text-sm font-semibold text-slate-900">{title}</div>
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <span className="truncate font-mono">{handle}</span>
              {c.contact?.roleGuess && <Badge tone="slate">{c.contact.roleGuess}</Badge>}
              {c.tgAccount && (
                <span className="flex items-center gap-1">
                  <span className="text-slate-300">·</span>
                  <Badge tone="sky">{c.tgAccount.label}</Badge>
                </span>
              )}
            </div>
          </div>
        </div>
        <div className="flex flex-shrink-0 items-center gap-2">
          <StatusDot status={c.status} />
          <ModeBadge mode={c.mode} />
          {c.campaign && (
            <Link
              to={`/campaigns/${c.campaign.id}`}
              className="hidden truncate text-xs text-brand-600 hover:text-brand-500 sm:inline"
            >
              {c.campaign.name}
            </Link>
          )}
          <Dropdown
            trigger={
              <button className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100">
                <EllipsisHorizontalIcon className="h-5 w-5" />
              </button>
            }
            items={[
              {
                label: 'Режим: auto',
                icon: <ChatBubbleLeftRightIcon className="h-4 w-4" />,
                onClick: () => modeMut.mutate('auto'),
              },
              {
                label: 'Режим: assisted',
                icon: <ChatBubbleLeftRightIcon className="h-4 w-4" />,
                onClick: () => modeMut.mutate('assisted'),
              },
              {
                label: 'Режим: manual',
                icon: <ChatBubbleLeftRightIcon className="h-4 w-4" />,
                onClick: () => modeMut.mutate('manual'),
              },
              {
                label: 'Поставить на паузу',
                onClick: () => statusMut.mutate('paused'),
              },
              {
                label: 'Закрыть как done',
                onClick: () => statusMut.mutate('done'),
              },
              {
                label: 'Открыть контакт',
                icon: <IdentificationIcon className="h-4 w-4" />,
                href: '/contacts',
              },
              {
                label: 'Открыть канал',
                icon: <HashtagIcon className="h-4 w-4" />,
                href: '/channels',
              },
            ]}
          />
        </div>
      </header>

      <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 py-5 scrollbar-thin">
        {msgsLoading ? (
          <div className="flex h-full items-center justify-center">
            <Spinner className="text-brand-500" />
          </div>
        ) : messages.length === 0 ? (
          <div className="mx-auto max-w-md rounded-xl bg-white p-6 text-center text-sm text-slate-500 ring-1 ring-slate-200">
            В диалоге пока нет сообщений. Когда придёт первое — оно появится здесь.
          </div>
        ) : (
          <div className="mx-auto max-w-3xl space-y-4">
            {dayGroups.map((g) => (
              <div key={g.day} className="space-y-3">
                <div className="my-2 flex items-center justify-center">
                  <span className="rounded-full bg-slate-200 px-3 py-0.5 text-[11px] font-medium text-slate-600">
                    {g.day}
                  </span>
                </div>
                {g.items.map((m) => (
                  <MessageBubble key={m.id} msg={m} />
                ))}
              </div>
            ))}
          </div>
        )}
      </div>

      {c.summary && (
        <div className="border-t border-slate-200 bg-amber-50/50 px-4 py-2 text-xs text-amber-800">
          <span className="font-semibold">Summary:</span> {c.summary}
        </div>
      )}

      <SuggestionTray
        conversationId={cId}
        suggestions={suggestions}
        onModeChange={(m) => modeMut.mutate(m)}
      />

      {c.lastInboundAt && (
        <div className="hidden">last inbound: {formatRelative(c.lastInboundAt)}</div>
      )}
    </div>
  );
}

function groupByDay(msgs: ChatMessage[]): { day: string; items: ChatMessage[] }[] {
  const map = new Map<string, ChatMessage[]>();
  for (const m of msgs) {
    const d = new Date(m.createdAt);
    const key = isNaN(d.getTime())
      ? 'без даты'
      : new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' }).format(d);
    const arr = map.get(key);
    if (arr) arr.push(m);
    else map.set(key, [m]);
  }
  return Array.from(map.entries()).map(([day, items]) => ({ day, items }));
}

// apps/web/src/features/inbox/ConversationView.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue';
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import Avatar from '../../components/Avatar.vue';
import Tag from '../../components/Tag.vue';
import Pill from '../../components/Pill.vue';
import Icon from '../../components/Icon.vue';
import Spinner from '../../components/Spinner.vue';
import Dropdown from '../../components/Dropdown.vue';
import MessageBubble from './MessageBubble.vue';
import SuggestionStrip from './SuggestionStrip.vue';
import { useRoom } from '../../lib/socket';
import { api } from '../../lib/api';
import { toast } from '../../lib/toast';
import { initials, formatRelative } from '../../lib/format';
import { avatarColor } from '../../lib/state';
import type { ChatMessage, ConversationDetail, ConversationListItem, Suggestion } from './types';

const props = defineProps<{
  conversation: ConversationListItem;
  showContext: boolean;
}>();

const emit = defineEmits<{ (e: 'toggleContext'): void }>();

const cId = computed(() => props.conversation.id);
const room = computed(() => `conversation:${cId.value}`);
const qc = useQueryClient();

const { data: details } = useQuery({
  queryKey: ['conversation', cId],
  queryFn: () => api.get<ConversationDetail>(`/conversations/${cId.value}`),
});

const { data: messages, isLoading: msgsLoading } = useQuery({
  queryKey: ['conversation-messages', cId],
  queryFn: () => api.get<ChatMessage[]>(`/conversations/${cId.value}/messages`),
});

const { data: suggestions } = useQuery({
  queryKey: ['conversation-suggestions', cId],
  queryFn: () => api.get<Suggestion[]>(`/conversations/${cId.value}/suggestions`),
});

const draft = ref('');
const scrollRef = ref<HTMLElement | null>(null);

useRoom(() => room.value, 'message.new', () => {
  qc.invalidateQueries({ queryKey: ['conversation-messages', cId.value] });
  qc.invalidateQueries({ queryKey: ['conversations'] });
});
useRoom(() => room.value, 'suggestion.new', () => {
  qc.invalidateQueries({ queryKey: ['conversation-suggestions', cId.value] });
});
useRoom(() => room.value, 'mode.changed', () => {
  qc.invalidateQueries({ queryKey: ['conversation', cId.value] });
});

watch(
  () => messages.value?.length,
  () => {
    nextTick(() => {
      if (scrollRef.value) scrollRef.value.scrollTop = scrollRef.value.scrollHeight;
    });
  },
);

watch(cId, () => { draft.value = ''; });

const c = computed<ConversationDetail>(() => details.value ?? (props.conversation as ConversationDetail));
const handle = computed(() => c.value.contact?.channel?.handle ?? c.value.contact?.value ?? '—');
const title = computed(() => c.value.contact?.channel?.title ?? c.value.contact?.value ?? 'Без названия');

const modeMut = useMutation({
  mutationFn: (mode: 'auto' | 'assisted' | 'manual') =>
    api.patch<void>(`/conversations/${cId.value}`, { mode }),
  onSuccess: (_v, mode) => {
    qc.invalidateQueries({ queryKey: ['conversation', cId.value] });
    qc.invalidateQueries({ queryKey: ['conversations'] });
    toast.success(`Режим: ${mode}`);
  },
});

const statusMut = useMutation({
  mutationFn: (status: 'active' | 'paused' | 'done' | 'failed') =>
    api.patch<void>(`/conversations/${cId.value}`, { status }),
  onSuccess: () => {
    qc.invalidateQueries({ queryKey: ['conversation', cId.value] });
    qc.invalidateQueries({ queryKey: ['conversations'] });
  },
});

const sendMut = useMutation({
  mutationFn: () => api.post<void>(`/conversations/${cId.value}/messages`, { text: draft.value }),
  onSuccess: () => {
    qc.invalidateQueries({ queryKey: ['conversation-messages', cId.value] });
    draft.value = '';
    toast.success('Сообщение поставлено в очередь');
  },
  onError: (e: Error) => toast.error('Не удалось отправить', e.message),
});

interface DayGroup { day: string; items: ChatMessage[] }

const groupedMessages = computed<DayGroup[]>(() => {
  const list = messages.value ?? [];
  const fmt = new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' });
  const map = new Map<string, ChatMessage[]>();
  for (const m of list) {
    const d = new Date(m.createdAt);
    const key = Number.isNaN(d.getTime()) ? 'без даты' : fmt.format(d);
    const arr = map.get(key);
    if (arr) arr.push(m); else map.set(key, [m]);
  }
  return Array.from(map.entries()).map(([day, items]) => ({ day, items }));
});

const dropdownItems = computed(() => [
  { label: 'Режим: auto', icon: 'play_circle' as const, onClick: () => modeMut.mutate('auto') },
  { label: 'Режим: assisted', icon: 'sparkle' as const, onClick: () => modeMut.mutate('assisted') },
  { label: 'Режим: manual', icon: 'user' as const, onClick: () => modeMut.mutate('manual') },
  { divider: true, label: '' },
  { label: 'Поставить на паузу', icon: 'pause_circle' as const, onClick: () => statusMut.mutate('paused') },
  { label: 'Закрыть как done', icon: 'check_circle' as const, onClick: () => statusMut.mutate('done') },
]);

function send(): void {
  if (draft.value.trim().length === 0) return;
  sendMut.mutate();
}

function onComposerKey(e: KeyboardEvent): void {
  if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') { e.preventDefault(); send(); }
}

function escalate(): void { modeMut.mutate('manual'); }
</script>

<template>
  <div style="display: flex; flex-direction: column; min-height: 0; min-width: 0; height: 100%;">
    <!-- Header -->
    <div style="height: var(--topbar); padding: 0 16px; display: flex; align-items: center; gap: 10px; border-bottom: 1px solid var(--line); flex: none;">
      <Avatar :text="initials(title)" size="lg" :color="avatarColor(c.id)" />
      <div style="min-width: 0;">
        <div style="display: flex; align-items: center; gap: 8px;">
          <span style="font-weight: 600; font-size: 13px;" class="ellipsis">{{ title }}</span>
          <Tag v-if="c.contact?.channel?.platform" :platform="c.contact.channel.platform" />
          <span class="mono muted-2">{{ handle }}</span>
        </div>
        <div v-if="c.contact?.channel" style="font-size: 11px; color: var(--ink-3); margin-top: 1px;" class="ellipsis">
          {{ c.contact.channel.title }} · {{ c.contact.channel.platform }}
        </div>
      </div>
      <div style="flex: 1;" />
      <Pill :state="c.status" />
      <Pill :state="c.mode" />
      <span class="divider-v" />
      <button class="btn ghost sm" @click="escalate" title="Эскалация на оператора">
        <Icon name="flag" :size="12" /><span>Эскалация</span>
      </button>
      <button class="btn ghost icon-only sm" :title="showContext ? 'Скрыть контекст' : 'Показать контекст'" @click="emit('toggleContext')">
        <Icon name="eye" :size="12" />
      </button>
      <Dropdown :items="dropdownItems" align="right">
        <button class="btn ghost icon-only sm"><Icon name="more" :size="12" /></button>
      </Dropdown>
    </div>

    <!-- Messages -->
    <div ref="scrollRef" style="flex: 1; overflow: auto; padding: 18px 22px; background: var(--paper);">
      <div v-if="c.campaign" style="display: flex; justify-content: center; margin-bottom: 14px;">
        <span style="font-size: 10.5px; color: var(--ink-4); font-family: var(--font-mono); padding: 2px 9px; background: var(--paper-3); border: 1px solid var(--line); border-radius: 999px;">
          кампания: {{ c.campaign.name }}
        </span>
      </div>

      <div v-if="msgsLoading" class="center"><Spinner /></div>
      <div v-else-if="!messages || messages.length === 0" style="max-width: 360px; margin: 32px auto; text-align: center; color: var(--ink-3); font-size: 12.5px;">
        В диалоге пока нет сообщений. Когда придёт первое — оно появится здесь.
      </div>
      <template v-else>
        <div v-for="g in groupedMessages" :key="g.day" style="margin-bottom: 8px;">
          <div style="display: flex; justify-content: center; margin: 4px 0 12px;">
            <span style="font-size: 10.5px; color: var(--ink-4); font-family: var(--font-mono); padding: 2px 9px; background: var(--paper-3); border: 1px solid var(--line); border-radius: 999px;">{{ g.day }}</span>
          </div>
          <MessageBubble v-for="m in g.items" :key="m.id" :msg="m" />
        </div>
      </template>
    </div>

    <!-- Summary banner -->
    <div v-if="c.summary" style="border-top: 1px solid var(--line); background: var(--warn-bg); color: var(--warn); padding: 6px 14px; font-size: 11.5px;">
      <strong>Summary:</strong> {{ c.summary }}
    </div>

    <!-- Suggestions -->
    <SuggestionStrip
      :conversation-id="cId"
      :suggestions="suggestions ?? []"
      @pick-to-draft="(t) => (draft = t)"
    />

    <!-- Composer -->
    <div style="padding: 10px 14px 14px; border-top: 1px solid var(--line); background: var(--paper); flex: none;">
      <div style="border: 1px solid var(--line-2); border-radius: 8px; background: var(--paper); overflow: hidden; box-shadow: var(--shadow-sm);">
        <textarea
          v-model="draft"
          @keydown="onComposerKey"
          placeholder="Напиши ответ или выбери подсказку выше · ⌘↩ — отправить"
          style="width: 100%; min-height: 78px; resize: vertical; border: none; outline: none; padding: 10px 12px; font-family: inherit; font-size: 13px; color: var(--ink); background: transparent; line-height: 1.5;"
        />
        <div style="display: flex; align-items: center; gap: 6px; padding: 6px 8px; border-top: 1px solid var(--line); background: var(--paper-2); flex-wrap: wrap;">
          <button class="btn ghost icon-only sm"><Icon name="paperclip" :size="12" /></button>
          <button class="btn ghost icon-only sm"><Icon name="smile" :size="12" /></button>
          <span class="divider-v" />
          <button class="btn ghost sm" title="Перефразировать"><Icon name="sparkle" :size="12" /></button>
          <button class="btn ghost sm" title="SafetyFilter"><Icon name="shield" :size="12" /></button>
          <div style="flex: 1; min-width: 8px;" />
          <button class="btn primary sm" :disabled="sendMut.isPending.value || !draft.trim()" @click="send">
            <Icon name="send" :size="11" /><span>Отправить</span><span class="kbd">⌘↩</span>
          </button>
        </div>
        <div v-if="c.tgAccount" style="padding: 0 10px 6px; display: flex; justify-content: flex-end;">
          <span class="muted-2" style="font-size: 10.5px;">с аккаунта <span class="mono">{{ c.tgAccount.label }}</span></span>
        </div>
      </div>
      <div v-if="c.lastInboundAt" style="display: none;">last inbound: {{ formatRelative(c.lastInboundAt) }}</div>
    </div>
  </div>
</template>
