// apps/web/src/features/inbox/InboxPage.tsx
import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { MagnifyingGlassIcon } from '@heroicons/react/24/outline';
import { Input } from '../../components/Input';
import { Select } from '../../components/Select';
import { ConversationList, type ConversationListItem } from './ConversationList';
import { ConversationView } from './ConversationView';
import { EmptyState } from '../../components/EmptyState';
import { api } from '../../lib/api';

export function InboxPage() {
  const { conversationId } = useParams<{ conversationId?: string }>();
  const nav = useNavigate();
  const [search, setSearch] = useState('');
  const [mode, setMode] = useState('');
  const [status, setStatus] = useState('');

  const { data: conversations = [] } = useQuery({
    queryKey: ['conversations', { search, mode, status }],
    queryFn: () => {
      const qs = new URLSearchParams();
      if (search) qs.set('q', search);
      if (mode) qs.set('mode', mode);
      if (status) qs.set('status', status);
      return api.get<ConversationListItem[]>(`/conversations?${qs.toString()}`);
    },
    refetchInterval: 30_000,
  });

  const current = useMemo(
    () => conversations.find((c) => c.id === conversationId) ?? null,
    [conversations, conversationId],
  );

  useEffect(() => {
    if (!conversationId && conversations[0]) {
      nav(`/inbox/${conversations[0].id}`, { replace: true });
    }
  }, [conversationId, conversations, nav]);

  return (
    <div className="-mx-4 -my-6 flex h-[calc(100vh-3.5rem)] md:-mx-6 md:-my-8">
      <aside className="flex w-80 flex-shrink-0 flex-col border-r border-slate-200 bg-white">
        <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3">
          <h1 className="text-base font-semibold text-slate-900">Диалоги</h1>
          <span className="text-xs text-slate-500">{conversations.length}</span>
        </div>
        <div className="space-y-2 border-b border-slate-200 px-3 py-3">
          <Input
            placeholder="Поиск…"
            leftIcon={<MagnifyingGlassIcon className="h-4 w-4" />}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <div className="flex gap-2">
            <Select
              className="flex-1"
              value={mode}
              onChange={(e) => setMode(e.target.value)}
              options={[
                { value: '', label: 'Все режимы' },
                { value: 'auto', label: 'auto' },
                { value: 'assisted', label: 'assisted' },
                { value: 'manual', label: 'manual' },
              ]}
            />
            <Select
              className="flex-1"
              value={status}
              onChange={(e) => setStatus(e.target.value)}
              options={[
                { value: '', label: 'Любой' },
                { value: 'active', label: 'Active' },
                { value: 'paused', label: 'Paused' },
                { value: 'done', label: 'Done' },
                { value: 'failed', label: 'Failed' },
              ]}
            />
          </div>
        </div>
        <ConversationList
          items={conversations}
          activeId={conversationId}
          onPick={(id) => nav(`/inbox/${id}`)}
        />
      </aside>
      <main className="flex min-w-0 flex-1 flex-col bg-slate-50">
        {current ? (
          <ConversationView conversation={current} />
        ) : (
          <div className="flex h-full items-center justify-center">
            <EmptyState
              title="Выберите диалог"
              description="Слева — список входящих и исходящих CustDev-диалогов."
            />
          </div>
        )}
      </main>
    </div>
  );
}

// apps/web/src/features/inbox/InboxPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useQuery } from '@tanstack/vue-query';
import ConversationList from './ConversationList.vue';
import ConversationView from './ConversationView.vue';
import ContextPanel from './ContextPanel.vue';
import EmptyState from '../../components/EmptyState.vue';
import { api } from '../../lib/api';
import type { ConversationListItem, Suggestion, ConversationDetail } from './types';

const route = useRoute();
const router = useRouter();

const showContext = ref(true);

const conversationId = computed(() => (route.params.conversationId as string | undefined) ?? undefined);

const { data: conversations } = useQuery({
  queryKey: ['conversations'],
  queryFn: () => api.get<ConversationListItem[]>('/conversations'),
  refetchInterval: 30_000,
});

const list = computed<ConversationListItem[]>(() => conversations.value ?? []);
const current = computed<ConversationListItem | null>(() => list.value.find((c) => c.id === conversationId.value) ?? null);

watch(
  [() => list.value, conversationId],
  ([items, id]) => {
    if (!id && items[0]) {
      router.replace(`/inbox/${items[0].id}`);
    }
  },
  { immediate: true },
);

const { data: details } = useQuery({
  queryKey: ['conversation', conversationId],
  queryFn: () => api.get<ConversationDetail>(`/conversations/${conversationId.value}`),
  enabled: computed(() => !!conversationId.value),
});

const { data: contextSuggestions } = useQuery({
  queryKey: ['conversation-suggestions', conversationId],
  queryFn: () => api.get<Suggestion[]>(`/conversations/${conversationId.value}/suggestions`),
  enabled: computed(() => !!conversationId.value),
});

function pick(id: string): void {
  router.push(`/inbox/${id}`);
}
</script>

<template>
  <div :style="{
    display: 'grid',
    gridTemplateColumns: showContext ? '320px 1fr 340px' : '320px 1fr',
    height: 'calc(100vh - var(--topbar))',
    minHeight: 0,
  }">
    <ConversationList :items="list" :active-id="conversationId" @pick="pick" />
    <template v-if="current">
      <ConversationView :conversation="current" :show-context="showContext" @toggle-context="showContext = !showContext" />
      <ContextPanel
        v-if="showContext && details"
        :conversation="details"
        :suggestions="contextSuggestions ?? []"
        @close="showContext = false"
      />
    </template>
    <template v-else>
      <div style="display: flex; align-items: center; justify-content: center; min-width: 0;">
        <EmptyState title="Выберите диалог" description="Слева — список входящих и исходящих CustDev-диалогов." icon="chat" />
      </div>
    </template>
  </div>
</template>
