// apps/web/src/features/inbox/MessageBubble.tsx
import { CheckIcon, ClockIcon, ExclamationTriangleIcon } from '@heroicons/react/24/outline';
import { Badge } from '../../components/Badge';
import { formatTime } from '../../lib/format';
import { cn } from '../../lib/cn';

export interface ChatMessage {
  id: string;
  /**
   * Prisma enum values are `in_` / `out_` (suffixed because `in`/`out` are reserved).
   */
  direction: 'in_' | 'out_';
  sender: 'contact' | 'ai' | 'operator' | 'system';
  text: string;
  status?: 'pending' | 'sending' | 'sent' | 'failed' | 'received';
  createdAt: string;
  sentAt?: string | null;
}

export function MessageBubble({ msg }: { msg: ChatMessage }) {
  const isOut = msg.direction === 'out_';
  const senderLabel =
    msg.sender === 'ai' ? 'AI' : msg.sender === 'operator' ? 'Operator' : msg.sender === 'system' ? 'System' : '';
  return (
    <div className={cn('flex w-full animate-fade-in', isOut ? 'justify-end' : 'justify-start')}>
      <div className={cn('max-w-[75%]', isOut ? 'items-end' : 'items-start')}>
        <div
          className={cn(
            'rounded-2xl px-4 py-2.5 text-sm shadow-sm ring-1',
            isOut
              ? 'rounded-br-md bg-brand-600 text-white ring-brand-600/40'
              : 'rounded-bl-md bg-white text-slate-900 ring-slate-200',
          )}
        >
          <p className="whitespace-pre-wrap break-words">{msg.text}</p>
        </div>
        <div
          className={cn(
            'mt-1 flex items-center gap-1.5 text-[11px] text-slate-400',
            isOut ? 'justify-end' : 'justify-start',
          )}
        >
          {senderLabel && (
            <Badge tone={msg.sender === 'ai' ? 'indigo' : msg.sender === 'operator' ? 'violet' : 'slate'}>
              {senderLabel}
            </Badge>
          )}
          <span>{formatTime(msg.sentAt ?? msg.createdAt)}</span>
          {isOut && msg.status && <StatusIcon status={msg.status} />}
        </div>
      </div>
    </div>
  );
}

function StatusIcon({ status }: { status: NonNullable<ChatMessage['status']> }) {
  if (status === 'failed') return <ExclamationTriangleIcon className="h-3.5 w-3.5 text-rose-500" />;
  if (status === 'pending' || status === 'sending') return <ClockIcon className="h-3.5 w-3.5 text-slate-400" />;
  return <CheckIcon className="h-3.5 w-3.5 text-emerald-500" />;
}

// apps/web/src/features/inbox/MessageBubble.vue
<script setup lang="ts">
import { computed } from 'vue';
import Icon from '../../components/Icon.vue';
import { formatTime } from '../../lib/format';
import type { ChatMessage } from './types';

const props = defineProps<{ msg: ChatMessage }>();

const isOut = computed(() => props.msg.direction === 'out_');
const senderLabel = computed(() => {
  switch (props.msg.sender) {
    case 'ai': return 'AI';
    case 'operator': return 'Operator';
    case 'system': return 'System';
    default: return '';
  }
});

const bubbleStyle = computed(() => ({
  background: isOut.value ? 'var(--ink)' : 'var(--paper-2)',
  color: isOut.value ? 'var(--paper)' : 'var(--ink)',
  border: isOut.value ? '1px solid var(--ink)' : '1px solid var(--line)',
  padding: '9px 12px',
  borderRadius: '10px',
  fontSize: '12.5px',
  lineHeight: '1.55',
  whiteSpace: 'pre-wrap' as const,
  wordBreak: 'break-word' as const,
}));
</script>

<template>
  <div :style="{ display: 'flex', justifyContent: isOut ? 'flex-end' : 'flex-start', marginBottom: '14px' }">
    <div style="max-width: 520px; min-width: 0;">
      <div :style="bubbleStyle">{{ msg.text }}</div>
      <div
        :style="{
          fontSize: '10.5px',
          color: 'var(--ink-4)',
          fontFamily: 'var(--font-mono)',
          marginTop: '3px',
          display: 'flex',
          gap: '8px',
          justifyContent: isOut ? 'flex-end' : 'flex-start',
          alignItems: 'center',
        }"
      >
        <span v-if="msg.agentName || senderLabel" style="color: var(--accent-2); display: inline-flex; align-items: center; gap: 3px;">
          <Icon name="zap" :size="9" />
          <span>{{ msg.agentName || senderLabel }}</span>
        </span>
        <span>{{ formatTime(msg.sentAt ?? msg.createdAt) }}</span>
        <template v-if="isOut && msg.status">
          <span v-if="msg.status === 'failed'" style="color: var(--bad); display: inline-flex;"><Icon name="warn" :size="10" /></span>
          <span v-else-if="msg.status === 'pending' || msg.status === 'sending'" style="color: var(--ink-4); display: inline-flex;"><Icon name="clock" :size="10" /></span>
          <span v-else style="color: var(--ok); display: inline-flex;"><Icon name="check" :size="10" /></span>
        </template>
      </div>
    </div>
  </div>
</template>
