// apps/web/src/features/channels/ChannelsPage.tsx
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  PlusIcon,
  ArrowDownTrayIcon,
  MagnifyingGlassIcon,
  ArrowPathIcon,
  ArrowTopRightOnSquareIcon,
} from '@heroicons/react/24/outline';
import { PageHeader } from '../../components/PageHeader';
import { Button } from '../../components/Button';
import { Input } from '../../components/Input';
import { Select } from '../../components/Select';
import { DataTable, type Column } from '../../components/DataTable';
import { Badge } from '../../components/Badge';
import { StatusDot } from '../../components/StatusDot';
import { ChannelImportDialog } from './ChannelImportDialog';
import { ChannelDetailDrawer } from './ChannelDetailDrawer';
import { useToast } from '../../components/Toast';
import { api } from '../../lib/api';
import { formatCompact, formatRelative } from '../../lib/format';

export interface Channel {
  id: string;
  platform: 'telegram' | 'instagram' | 'youtube';
  handle: string;
  title: string;
  description?: string;
  followers?: number;
  language?: string;
  status: string;
  /** Prisma-style include from `findMany`. */
  _count?: { contacts: number };
  source?: string;
  scrapedAt?: string;
  createdAt: string;
  updatedAt?: string;
  /** `red_flags` is intentional snake_case in the analysis schema. */
  analysis?: { topic?: string; tone?: string; red_flags?: string[] } | null;
  lastError?: string | null;
}

export function ChannelsPage() {
  const qc = useQueryClient();
  const toast = useToast();
  const [search, setSearch] = useState('');
  const [platform, setPlatform] = useState('');
  const [status, setStatus] = useState('');
  const [importOpen, setImportOpen] = useState(false);
  const [selected, setSelected] = useState<Channel | null>(null);

  const { data, isLoading } = useQuery({
    queryKey: ['channels', { search, platform, status }],
    queryFn: () => {
      const qs = new URLSearchParams();
      if (search) qs.set('q', search);
      if (platform) qs.set('platform', platform);
      if (status) qs.set('status', status);
      return api.get<{ items: Channel[]; total: number } | Channel[]>(`/channels?${qs.toString()}`);
    },
  });

  const channels = useMemo<Channel[]>(() => {
    if (!data) return [];
    if (Array.isArray(data)) return data;
    return data.items;
  }, [data]);

  const scrapeMut = useMutation({
    mutationFn: (id: string) => api.post<void>(`/channels/${id}/scrape`, {}),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['channels'] });
      toast.info('Перезапуск скрейпа поставлен в очередь');
    },
  });

  const columns: Column<Channel>[] = [
    {
      key: 'channel',
      header: 'Канал',
      cell: (r) => (
        <div className="flex items-start gap-3">
          <div className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-xl bg-slate-100 text-xs font-semibold text-slate-700">
            {(r.title || r.handle || '?').slice(0, 2).toUpperCase()}
          </div>
          <div className="min-w-0">
            <div className="truncate font-medium text-slate-900">{r.title || r.handle}</div>
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <Badge tone={platformTone(r.platform)}>{r.platform}</Badge>
              <span className="truncate font-mono">{r.handle}</span>
            </div>
          </div>
        </div>
      ),
    },
    {
      key: 'status',
      header: 'Статус',
      cell: (r) => <StatusDot status={r.status} />,
    },
    {
      key: 'topic',
      header: 'Тема',
      cell: (r) => (
        <div className="text-xs text-slate-700">
          {r.analysis?.topic ? (
            <Badge tone="indigo">{r.analysis.topic}</Badge>
          ) : (
            <span className="text-slate-400">—</span>
          )}
          {r.analysis?.red_flags?.length ? (
            <Badge tone="rose" className="ml-1">
              red flags
            </Badge>
          ) : null}
        </div>
      ),
    },
    {
      key: 'followers',
      header: 'Подписчики',
      align: 'right',
      cell: (r) => <span className="text-sm tabular-nums text-slate-700">{formatCompact(r.followers ?? null)}</span>,
    },
    {
      key: 'contacts',
      header: 'Контакты',
      align: 'right',
      cell: (r) => (
        <span className="text-sm tabular-nums text-slate-700">{r._count?.contacts ?? 0}</span>
      ),
    },
    {
      key: 'scraped',
      header: 'Скрейп',
      cell: (r) => <span className="text-xs text-slate-500">{formatRelative(r.scrapedAt)}</span>,
    },
    {
      key: 'actions',
      header: '',
      align: 'right',
      cell: (r) => (
        <div className="flex items-center justify-end gap-1">
          <button
            className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100"
            onClick={(e) => {
              e.stopPropagation();
              scrapeMut.mutate(r.id);
            }}
            title="Перезапустить скрейп"
          >
            <ArrowPathIcon className="h-4 w-4" />
          </button>
          <button
            className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100"
            onClick={(e) => {
              e.stopPropagation();
              setSelected(r);
            }}
            title="Открыть"
          >
            <ArrowTopRightOnSquareIcon className="h-4 w-4" />
          </button>
        </div>
      ),
    },
  ];

  return (
    <div>
      <PageHeader
        title="Каналы"
        description="Все загруженные каналы. Один канал — N контактов с приоритетом."
        actions={
          <>
            <Button
              variant="secondary"
              leftIcon={<ArrowDownTrayIcon className="h-4 w-4" />}
              onClick={() => toast.info('Экспорт CSV', 'Скачивание начнётся через секунду')}
            >
              Экспорт CSV
            </Button>
            <Button leftIcon={<PlusIcon className="h-4 w-4" />} onClick={() => setImportOpen(true)}>
              Импорт каналов
            </Button>
          </>
        }
      />

      <div className="card mb-4 p-4">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-4">
          <Input
            placeholder="Поиск по handle / названию"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            leftIcon={<MagnifyingGlassIcon className="h-4 w-4" />}
          />
          <Select
            value={platform}
            onChange={(e) => setPlatform(e.target.value)}
            options={[
              { value: '', label: 'Все платформы' },
              { value: 'telegram', label: 'Telegram' },
              { value: 'instagram', label: 'Instagram' },
              { value: 'youtube', label: 'YouTube' },
            ]}
          />
          <Select
            value={status}
            onChange={(e) => setStatus(e.target.value)}
            options={[
              { value: '', label: 'Любой статус' },
              { value: 'new', label: 'New' },
              { value: 'scraping', label: 'Scraping' },
              { value: 'scraped', label: 'Scraped' },
              { value: 'extracting', label: 'Extracting' },
              { value: 'extracted', label: 'Extracted' },
              { value: 'ready', label: 'Ready' },
              { value: 'failed', label: 'Failed' },
              { value: 'disqualified', label: 'Disqualified' },
            ]}
          />
          <div className="text-right text-xs text-slate-500 sm:self-end">
            Найдено: <span className="font-medium text-slate-900">{channels.length}</span>
          </div>
        </div>
      </div>

      <DataTable
        columns={columns}
        rows={channels}
        loading={isLoading}
        rowKey={(r) => r.id}
        onRowClick={(r) => setSelected(r)}
        emptyTitle="Каналов пока нет"
        emptyDescription="Импортируйте список или вставьте handle-ы вручную."
        emptyAction={
          <Button leftIcon={<PlusIcon className="h-4 w-4" />} onClick={() => setImportOpen(true)}>
            Импорт
          </Button>
        }
      />

      <ChannelImportDialog
        open={importOpen}
        onClose={() => setImportOpen(false)}
        onDone={() => {
          qc.invalidateQueries({ queryKey: ['channels'] });
          setImportOpen(false);
          toast.success('Каналы поставлены в очередь скрейпа');
        }}
      />
      <ChannelDetailDrawer
        channel={selected}
        onClose={() => setSelected(null)}
        onAction={() => qc.invalidateQueries({ queryKey: ['channels'] })}
      />
    </div>
  );
}

function platformTone(p: string): 'sky' | 'rose' | 'violet' | 'gray' {
  if (p === 'telegram') return 'sky';
  if (p === 'instagram') return 'rose';
  if (p === 'youtube') return 'rose';
  return 'gray';
}

// apps/web/src/features/channels/ChannelsPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query';
import PageHead from '../../components/PageHead.vue';
import Tabs from '../../components/Tabs.vue';
import FilterBar from '../../components/FilterBar.vue';
import Chip from '../../components/Chip.vue';
import Pill from '../../components/Pill.vue';
import Tag from '../../components/Tag.vue';
import Avatar from '../../components/Avatar.vue';
import Bar from '../../components/Bar.vue';
import Icon from '../../components/Icon.vue';
import Spinner from '../../components/Spinner.vue';
import EmptyState from '../../components/EmptyState.vue';
import ChannelImportDialog from './ChannelImportDialog.vue';
import ChannelDetailDrawer from './ChannelDetailDrawer.vue';
import { api } from '../../lib/api';
import { toast } from '../../lib/toast';
import { formatCompact, initials, formatRelative } from '../../lib/format';
import { avatarColor } from '../../lib/state';
import type { Channel } from './types';

const qc = useQueryClient();

const tab = ref<'all' | 'scraping' | 'extracted' | 'needs_review' | 'failed'>('all');
const search = ref('');
const platformFilter = ref<'' | 'telegram' | 'instagram' | 'youtube'>('');
const langFilter = ref<'' | 'ru' | 'en'>('ru');
const minSubs = ref<'' | '1k' | '5k' | '10k'>('5k');

const importOpen = ref(false);
const selected = ref<Channel | null>(null);

const queryKey = computed(() => ['channels', { tab: tab.value, search: search.value, platform: platformFilter.value }] as const);

const { data, isLoading } = useQuery({
  queryKey,
  queryFn: () => {
    const qs = new URLSearchParams();
    if (search.value) qs.set('q', search.value);
    if (platformFilter.value) qs.set('platform', platformFilter.value);
    if (tab.value !== 'all') qs.set('status', tab.value);
    return api.get<{ items: Channel[]; total: number } | Channel[]>(`/channels?${qs.toString()}`);
  },
});

const channels = computed<Channel[]>(() => {
  const d = data.value;
  if (!d) return [];
  if (Array.isArray(d)) return d;
  return d.items;
});

const filteredChannels = computed<Channel[]>(() => {
  let xs = channels.value;
  if (langFilter.value) xs = xs.filter((c) => (c.language ?? '').toLowerCase() === langFilter.value);
  if (minSubs.value) {
    const min = minSubs.value === '1k' ? 1000 : minSubs.value === '5k' ? 5000 : 10000;
    xs = xs.filter((c) => (c.followers ?? 0) >= min);
  }
  return xs;
});

const counts = computed(() => {
  const all = channels.value.length;
  return {
    all,
    scraping: channels.value.filter((c) => c.status === 'scraping').length,
    extracted: channels.value.filter((c) => c.status === 'extracted' || c.status === 'ready').length,
    needs_review: channels.value.filter((c) => c.status === 'needs_review' || c.status === 'new').length,
    failed: channels.value.filter((c) => c.status === 'failed').length,
  };
});

const scrapeAllMut = useMutation({
  mutationFn: async () => {
    const ids = channels.value.map((c) => c.id);
    await Promise.all(ids.map((id) => api.post<void>(`/channels/${id}/scrape`, {}).catch(() => undefined)));
  },
  onSuccess: () => {
    toast.info('Скрейп поставлен в очередь', `${channels.value.length} каналов`);
    qc.invalidateQueries({ queryKey: ['channels'] });
  },
});

const tabsList = computed(() => [
  { id: 'all', label: 'Все', count: counts.value.all },
  { id: 'scraping', label: 'Скрейпинг', count: counts.value.scraping },
  { id: 'extracted', label: 'Готовы', count: counts.value.extracted },
  { id: 'needs_review', label: 'Ревью', count: counts.value.needs_review },
  { id: 'failed', label: 'Ошибки', count: counts.value.failed },
]);
</script>

<template>
  <PageHead title="Каналы" :sub="`${counts.all} каналов · 3 платформы`">
    <template #actions>
      <button class="btn" @click="importOpen = true"><Icon name="upload" :size="12" /><span>Импорт</span></button>
      <button class="btn" :disabled="scrapeAllMut.isPending.value" @click="scrapeAllMut.mutate()">
        <span v-if="scrapeAllMut.isPending.value" class="spinner" />
        <Icon v-else name="refresh" :size="12" /><span>Перескрейпить</span>
      </button>
      <button class="btn primary" @click="importOpen = true">
        <Icon name="plus" :size="12" /><span>Добавить канал</span><span class="kbd">N</span>
      </button>
    </template>
  </PageHead>
  <Tabs :tabs="tabsList" :active="tab" @change="(id) => (tab = id as any)" />
  <FilterBar>
    <Chip
      :label="'Платформа'"
      :value="platformFilter || 'любая'"
      :applied="!!platformFilter"
      removable
      @click="platformFilter = (platformFilter === '' ? 'telegram' : platformFilter === 'telegram' ? 'instagram' : platformFilter === 'instagram' ? 'youtube' : '') as any"
      @remove="platformFilter = ''"
    />
    <Chip
      label="Язык"
      :value="langFilter || 'любой'"
      :applied="!!langFilter"
      tone="ok"
      removable
      @click="langFilter = langFilter === 'ru' ? 'en' : langFilter === 'en' ? '' : 'ru'"
      @remove="langFilter = ''"
    />
    <Chip
      label="Подписчики"
      :value="minSubs ? `≥ ${minSubs.toUpperCase()}` : 'любые'"
      :applied="!!minSubs"
      removable
      @click="minSubs = minSubs === '5k' ? '10k' : minSubs === '10k' ? '1k' : '5k'"
      @remove="minSubs = ''"
    />
    <template #right>
      <span class="muted-2">{{ filteredChannels.length }} из {{ channels.length }}</span>
    </template>
  </FilterBar>

  <div v-if="isLoading" class="center"><Spinner /></div>
  <EmptyState
    v-else-if="filteredChannels.length === 0"
    title="Каналов нет"
    description="Импортируйте список или вставьте handle-ы вручную."
    icon="layers"
  >
    <template #action>
      <button class="btn primary" @click="importOpen = true"><Icon name="plus" :size="12" /><span>Импорт</span></button>
    </template>
  </EmptyState>
  <div v-else class="table-wrap">
    <table class="tbl">
      <thead>
        <tr>
          <th style="width: 28px;"><input type="checkbox" /></th>
          <th>Канал</th>
          <th>Платф.</th>
          <th>Тематика</th>
          <th style="text-align: right;">Подп.</th>
          <th>Скрейп</th>
          <th>Контакты</th>
          <th>Статус</th>
          <th>Добавлен</th>
          <th style="width: 28px;"></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="c in filteredChannels" :key="c.id" class="clickable" @click="selected = c">
          <td @click.stop><input type="checkbox" /></td>
          <td>
            <div style="display: flex; align-items: center; gap: 9px;">
              <Avatar :text="initials(c.title || c.handle)" :color="avatarColor(c.id)" />
              <div>
                <div class="cell-strong">{{ c.title || c.handle }}</div>
                <div class="mono muted-2" style="font-size: 10.5px;">{{ c.handle }}</div>
              </div>
            </div>
          </td>
          <td><Tag :platform="c.platform" /></td>
          <td class="muted">{{ c.analysis?.topic ?? '—' }}</td>
          <td class="mono" style="text-align: right;">{{ formatCompact(c.followers ?? null) }}</td>
          <td>
            <template v-if="c.status === 'scraping'">
              <div style="display: flex; align-items: center; gap: 6px;">
                <Bar :value="0.5" pct :width="60" />
                <span class="mono muted-2" style="font-size: 10.5px;">…</span>
              </div>
            </template>
            <span v-else-if="c.status === 'failed'" class="muted-2 mono" style="font-size: 10.5px;">error</span>
            <span v-else class="muted-2 mono" style="font-size: 10.5px;">{{ formatRelative(c.scrapedAt ?? null) }}</span>
          </td>
          <td>
            <span v-if="(c._count?.contacts ?? 0) > 0" style="display: inline-flex; gap: 4px; align-items: center;">
              <span class="mono cell-strong">{{ c._count!.contacts }}</span>
              <span class="muted-2">контакт{{ c._count!.contacts > 1 ? 'ов' : '' }}</span>
            </span>
            <span v-else class="muted-2">—</span>
          </td>
          <td><Pill :state="c.status" /></td>
          <td class="muted-2 mono" style="font-size: 10.5px;">{{ formatRelative(c.createdAt) }}</td>
          <td @click.stop>
            <button class="btn ghost icon-only sm"><Icon name="more" :size="12" /></button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <ChannelImportDialog
    :open="importOpen"
    @close="importOpen = false"
    @done="() => { importOpen = false; qc.invalidateQueries({ queryKey: ['channels'] }); }"
  />
  <ChannelDetailDrawer :channel="selected" @close="selected = null" @action="qc.invalidateQueries({ queryKey: ['channels'] })" />
</template>
