// apps/web/src/features/channels/ChannelImportDialog.tsx
import { useState, useRef } from 'react';
import { useMutation } from '@tanstack/react-query';
import { ArrowUpTrayIcon } from '@heroicons/react/24/outline';
import { Modal } from '../../components/Modal';
import { Textarea } from '../../components/Textarea';
import { Select } from '../../components/Select';
import { Button } from '../../components/Button';
import { useToast } from '../../components/Toast';
import { api } from '../../lib/api';

interface Props {
  open: boolean;
  onClose: () => void;
  onDone: () => void;
}

export function ChannelImportDialog({ open, onClose, onDone }: Props) {
  const toast = useToast();
  const [text, setText] = useState('');
  const [platformHint, setPlatformHint] = useState<'auto' | 'telegram' | 'instagram' | 'youtube'>('auto');
  const fileRef = useRef<HTMLInputElement>(null);

  const mut = useMutation({
    mutationFn: () => {
      const lines = text
        .split(/[\n,]+/)
        .map((s) => s.trim())
        .filter(Boolean);
      return api.post<{ accepted: number; skipped: number }>('/channels/import', {
        items: lines,
        platform_hint: platformHint === 'auto' ? undefined : platformHint,
      });
    },
    onSuccess: (r) => {
      toast.success('Импорт принят', `${r.accepted} новых, ${r.skipped} пропущено`);
      setText('');
      onDone();
    },
    onError: (e: Error) => toast.error('Ошибка импорта', e.message),
  });

  function onPickFile(): void {
    fileRef.current?.click();
  }

  function onFile(e: React.ChangeEvent<HTMLInputElement>): void {
    const f = e.target.files?.[0];
    if (!f) return;
    f.text().then((t) => setText(t));
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      size="lg"
      title="Импорт каналов"
      description="Каждая строка — handle (TG @x, IG instagram.com/y, YT youtube.com/@z) или ссылка."
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={mut.isPending}>
            Отмена
          </Button>
          <Button onClick={() => mut.mutate()} loading={mut.isPending} disabled={!text.trim()}>
            Импортировать
          </Button>
        </>
      }
    >
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <div className="sm:col-span-2">
          <Select
            label="Платформа"
            value={platformHint}
            onChange={(e) => setPlatformHint(e.target.value as typeof platformHint)}
            options={[
              { value: 'auto', label: 'Авто-определение' },
              { value: 'telegram', label: 'Telegram' },
              { value: 'instagram', label: 'Instagram' },
              { value: 'youtube', label: 'YouTube' },
            ]}
          />
        </div>
        <div className="flex items-end">
          <Button
            variant="secondary"
            className="w-full"
            leftIcon={<ArrowUpTrayIcon className="h-4 w-4" />}
            onClick={onPickFile}
          >
            Загрузить CSV
          </Button>
          <input ref={fileRef} type="file" accept=".csv,.txt" className="hidden" onChange={onFile} />
        </div>
      </div>
      <Textarea
        className="mt-4"
        rows={10}
        fontMono
        label="Список (каждая строка — один канал)"
        placeholder={`@founders_diary\ninstagram.com/anya_travels\nhttps://youtube.com/@nosquare`}
        value={text}
        onChange={(e) => setText(e.target.value)}
      />
      <p className="mt-2 text-xs text-slate-500">
        Дубликаты по (platform, external_id) объединяются. Для тяжёлого импорта используйте API.
      </p>
    </Modal>
  );
}

// apps/web/src/features/channels/ChannelImportDialog.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useMutation } from '@tanstack/vue-query';
import Modal from '../../components/Modal.vue';
import Field from '../../components/Field.vue';
import SelectInput from '../../components/SelectInput.vue';
import TextareaInput from '../../components/TextareaInput.vue';
import Icon from '../../components/Icon.vue';
import { api } from '../../lib/api';
import { toast } from '../../lib/toast';

const props = defineProps<{ open: boolean }>();
const emit = defineEmits<{ (e: 'close'): void; (e: 'done'): void }>();

const text = ref('');
const platformHint = ref<'auto' | 'telegram' | 'instagram' | 'youtube'>('auto');
const fileInput = ref<HTMLInputElement | null>(null);

const mut = useMutation({
  mutationFn: async () => {
    const lines = text.value.split(/[\n,]+/).map((s) => s.trim()).filter(Boolean);
    return api.post<{ accepted: number; skipped: number }>('/channels/import', {
      items: lines,
      platform_hint: platformHint.value === 'auto' ? undefined : platformHint.value,
    });
  },
  onSuccess: (r) => {
    toast.success('Импорт принят', `${r.accepted} новых, ${r.skipped} пропущено`);
    text.value = '';
    emit('done');
  },
  onError: (e: Error) => toast.error('Ошибка импорта', e.message),
});

function pickFile(): void { fileInput.value?.click(); }

function onFile(e: Event): void {
  const f = (e.target as HTMLInputElement).files?.[0];
  if (!f) return;
  f.text().then((t) => (text.value = t));
}
</script>

<template>
  <Modal
    :open="props.open"
    title="Импорт каналов"
    description="Каждая строка — handle (TG @x, IG instagram.com/y, YT youtube.com/@z) или ссылка."
    size="lg"
    @close="emit('close')"
  >
    <div style="display: grid; gap: 12px; grid-template-columns: 1fr 180px;">
      <Field label="Платформа">
        <SelectInput
          v-model="platformHint as string"
          :options="[
            { value: 'auto', label: 'Авто-определение' },
            { value: 'telegram', label: 'Telegram' },
            { value: 'instagram', label: 'Instagram' },
            { value: 'youtube', label: 'YouTube' },
          ]"
        />
      </Field>
      <Field label="Файл">
        <button class="btn block" type="button" @click="pickFile">
          <Icon name="upload" :size="12" /><span>Загрузить CSV</span>
        </button>
        <input ref="fileInput" type="file" accept=".csv,.txt" class="hidden" @change="onFile" />
      </Field>
    </div>
    <Field label="Список (каждая строка — один канал)" help="Дубликаты по (platform, external_id) объединяются.">
      <TextareaInput
        v-model="text"
        :rows="12"
        mono
        placeholder="@founders_diary&#10;instagram.com/anya_travels&#10;https://youtube.com/@nosquare"
      />
    </Field>
    <template #footer>
      <button class="btn" type="button" :disabled="mut.isPending.value" @click="emit('close')">Отмена</button>
      <button
        class="btn primary"
        type="button"
        :disabled="mut.isPending.value || !text.trim()"
        @click="mut.mutate()"
      >
        <span v-if="mut.isPending.value" class="spinner" />
        <Icon v-else name="upload" :size="12" />
        <span>Импортировать</span>
      </button>
    </template>
  </Modal>
</template>
